/**
 * Managed Vibe Coding Department — Type Definitions
 *
 * Types for the aiPLUG builder lifecycle:
 *   Phase A: Vibe Session (conversational requirements gathering)
 *   Phase B: Build Pipeline (scaffold → code → style → test → deploy)
 *   Phase C: Iterate (feedback loop until ship-ready)
 */

// ---------------------------------------------------------------------------
// aiPLUG Specification — What gets built
// ---------------------------------------------------------------------------

export interface AiPlugSpec {
  /** User-chosen name for their aiPLUG */
  name: string;

  /** One-sentence description of what it does */
  description: string;

  /** Who is this for */
  target_user: string;

  /** Design vibe: minimal, bold, playful, enterprise, etc. */
  design_vibe: string;

  /** Color preferences or brand colors */
  colors?: string[];

  /** Design inspirations (URLs, app names) */
  inspirations?: string[];

  /** Must-have features for v1 */
  features: string[];

  /** Nice-to-have features (deferred) */
  deferred_features?: string[];

  /** Tech stack (recommended or user-overridden) */
  tech_stack: TechStackRecommendation;

  /** Type of aiPLUG */
  plug_type: AiPlugType;
}

export type AiPlugType =
  | 'landing-page'        // Single page, marketing site
  | 'web-app'             // Multi-page interactive app
  | 'api-service'         // Backend-only API
  | 'full-stack'          // Frontend + backend + database
  | 'tool'                // Single-purpose utility
  | 'dashboard'           // Data display + admin panel
  | 'marketplace'         // Multi-vendor platform
  | 'saas';               // Full SaaS product

// ---------------------------------------------------------------------------
// Tech Stack Recommendation
// ---------------------------------------------------------------------------

export interface TechStackRecommendation {
  frontend: string;       // e.g. "Next.js 15", "React + Vite"
  backend: string;        // e.g. "Express", "Hono", "Next.js API Routes"
  database: string;       // e.g. "PostgreSQL + Prisma", "Firebase", "SQLite"
  hosting: string;        // e.g. "Cloud Run", "Vercel", "VPS"
  styling: string;        // e.g. "Tailwind CSS", "Stitch Nano (internal)"
  auth?: string;          // e.g. "NextAuth.js", "Firebase Auth", "Clerk"
  payments?: string;      // e.g. "Stripe", "LemonSqueezy"
  rationale: string;      // Why this stack was chosen
}

// ---------------------------------------------------------------------------
// Vibe Session Data — Collected during Phase A
// ---------------------------------------------------------------------------

export interface VibeSessionData {
  /** Step 1: Vision */
  vision: string;
  target_user: string;

  /** Step 2: Vibe */
  design_vibe: string;
  colors: string[];
  inspirations: string[];

  /** Step 3: Features */
  features: string[];
  deferred_features: string[];

  /** Step 4: Stack */
  tech_stack: TechStackRecommendation;

  /** Step 5: Confirmation */
  confirmed: boolean;
  plug_name: string;
  plug_type: AiPlugType;
}

// ---------------------------------------------------------------------------
// Build Manifest — What Chicken Hawk receives
// ---------------------------------------------------------------------------

export interface BuildManifest {
  manifest_id: string;
  shift_id: string;
  department: 'vibe-coding';
  aiPlug: AiPlugSpec;

  /** Build configuration */
  build_config: {
    /** Execution mode for the build */
    mode: 'sync' | 'async-job';

    /** Cloud Run Job ID for async builds */
    cloud_run_job?: string;

    /** Maximum build time in seconds */
    timeout_seconds: number;

    /** Whether to deploy a preview */
    deploy_preview: boolean;

    /** E2B sandbox template for code execution */
    sandbox_template?: string;
  };

  /** Pipeline plan — generated by Vibe_Ang */
  plan: {
    waves: BuildWave[];
    estimated_luc: number;
  };

  /** Metadata */
  user_id: string;
  session_id: string;
  created_at: string;
}

export interface BuildWave {
  wave_id: string;
  name: string;
  steps: BuildStep[];
}

export interface BuildStep {
  step_id: string;
  description: string;
  assigned_to: string;  // Lil_Hawk handle
  keywords: string[];   // STEP_AGENT_MAP keywords
  inputs: Record<string, unknown>;
  expected_output: string;
}

// ---------------------------------------------------------------------------
// Build Result — What comes back
// ---------------------------------------------------------------------------

export interface BuildResult {
  manifest_id: string;
  status: 'success' | 'partial' | 'failed';
  preview_url?: string;
  artifacts: BuildArtifact[];
  verification: VerificationReport;
  receipt_id: string;
  build_duration_ms: number;
}

export interface BuildArtifact {
  name: string;
  type: 'source-code' | 'config' | 'asset' | 'container-image' | 'preview-url';
  path: string;
  size_bytes?: number;
}

export interface VerificationReport {
  oracle_score: number;
  gates_passed: string[];
  gates_failed: string[];
  lint_clean: boolean;
  types_clean: boolean;
  tests_passed: number;
  tests_failed: number;
  accessibility_score?: number;
}
