/**
 * Per|Form NFL Draft Seed Data — 2026 NFL Draft
 *
 * Top draft-eligible prospects and NFL team needs.
 * This seed data bootstraps the draft engine. Once seeded,
 * prospects are enriched via Brave Search and CFBD API.
 *
 * Tiers:
 *   TOP_5     — Consensus top 5 pick
 *   TOP_15    — First half of round 1
 *   FIRST_ROUND — Late round 1
 *   DAY_2     — Rounds 2-3
 *   DAY_3     — Rounds 4-7
 *   PRIORITY_UDFA — Top undrafted free agents
 *   UDFA      — Undrafted free agent
 */

export interface SeedDraftProspect {
  firstName: string;
  lastName: string;
  position: string;
  college: string;
  conference?: string;
  classYear: string;
  eligibility?: string;
  height?: string;
  weight?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  overallRank: number;
  positionRank: number;
  trend: string;
  scoutMemo?: string;
  tags?: string;
  comparisons?: string;
  collegeStats?: string;
  combineInvite?: boolean;
  seniorBowl?: boolean;
  projectedRound?: number;
  projectedPick?: number;
  bullCase?: string;
  bearCase?: string;
  mediationVerdict?: string;
  debateWinner?: string;
  enrichedBy?: string;
}

// ─────────────────────────────────────────────────────────────
// Top 50 Draft Prospects (Seed — enriched via Brave Search)
// ─────────────────────────────────────────────────────────────

export const SEED_DRAFT_PROSPECTS: SeedDraftProspect[] = [
  {
    firstName: 'Shedeur',
    lastName: 'Sanders',
    position: 'QB',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'2\"",
    weight: 215,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 93,
    athleticism: 88,
    intangibles: 96,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Elite pocket passer with exceptional processing speed and accuracy. Led Colorado's resurgence under his father Deion Sanders. Poise under pressure is NFL-ready. Questions about arm strength on deep out routes but anticipation compensates.",
    tags: JSON.stringify(['pocket-passer', 'accuracy', 'poise', 'football-iq', 'leadership']),
    comparisons: JSON.stringify(['Dak Prescott processing', 'Kirk Cousins accuracy']),
    collegeStats: JSON.stringify({ 'Pass Yards': '4,134', 'Pass TD': 37, 'INT': 10, 'Comp %': '71.5%', 'QBR': 88.2 }),
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 1,
    bullCase: "Sanders is the most pro-ready QB in this class. His accuracy, processing, and leadership are all top-tier. He's been the face of a program and handled it with grace.",
    bearCase: "Arm strength is a concern on NFL deep throws. Colorado's competition level wasn't consistently elite. Father's presence could be a distraction at the next level.",
    mediationVerdict: "Bull wins. The arm strength concern is valid but manageable — he's not Mahomes but he's Brees-level accurate. QB1.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Cam',
    lastName: 'Ward',
    position: 'QB',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'2\"",
    weight: 223,
    paiScore: 93,
    tier: 'TOP_5',
    performance: 92,
    athleticism: 92,
    intangibles: 90,
    overallRank: 2,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: "Dynamic dual-threat QB with the best raw arm talent in the class. Transfer from Washington State to Miami showcased his ability to elevate to elite competition. Gunslinger mentality leads to turnovers but also big plays.",
    tags: JSON.stringify(['arm-talent', 'dual-threat', 'gunslinger', 'big-play']),
    comparisons: JSON.stringify(['Patrick Mahomes improvisation', 'Brett Favre gunslinger']),
    collegeStats: JSON.stringify({ 'Pass Yards': '4,313', 'Pass TD': 39, 'INT': 7, 'Rush Yards': 282, 'Rush TD': 5 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 2,
    bullCase: "Ward has the highest ceiling of any QB. His arm talent is generational and he showed at Miami he can handle the biggest stage.",
    bearCase: "Turnover-prone and relies too much on improvisation. Multiple transfers show restlessness. Decision-making under structure is inconsistent.",
    mediationVerdict: "Bull takes it. The turnovers are coachable, the arm isn't teachable. Risk/reward favors drafting him top 5.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Travis',
    lastName: 'Hunter',
    position: 'CB',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 185,
    paiScore: 97,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 96,
    intangibles: 97,
    overallRank: 3,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Generational two-way player — elite as both CB and WR. Heisman Trophy winner. The best college football player in a decade. Every-snap player who never comes off the field. Historic talent.",
    tags: JSON.stringify(['two-way', 'generational', 'heisman', 'ironman', 'elite-ball-skills']),
    comparisons: JSON.stringify(['Champ Bailey coverage', 'Deion Sanders ball skills', 'Charles Woodson versatility']),
    collegeStats: JSON.stringify({ 'INT': 4, 'PBU': 11, 'Receptions': 92, 'Rec Yards': '1,152', 'Rec TD': 14 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 3,
    bullCase: "Hunter is the best prospect in a decade. Two-way ability is unprecedented in the modern era. Heisman winner. He will impact day 1 on either side of the ball.",
    bearCase: "Playing both ways is unsustainable in the NFL. Which position is he? If CB, the receiving stats are irrelevant. If WR, his route-running needs work.",
    mediationVerdict: "Bull wins overwhelmingly. He's a CB who can also play WR — that's not a weakness, it's a cheat code. Generational.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Abdul',
    lastName: 'Carter',
    position: 'EDGE',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 252,
    paiScore: 93,
    tier: 'TOP_5',
    performance: 92,
    athleticism: 95,
    intangibles: 90,
    overallRank: 4,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Elite edge rusher with LB versatility. Converted from LB to EDGE and immediately became one of the best pass rushers in the nation. Explosive first step, bend, and power. Motor runs hot.",
    tags: JSON.stringify(['edge-rusher', 'versatile', 'explosive', 'motor', 'converted-lb']),
    comparisons: JSON.stringify(['Micah Parsons versatility', 'Von Miller bend']),
    collegeStats: JSON.stringify({ 'Sacks': 12, 'TFL': 19, 'Tackles': 67, 'FF': 3, 'QB Hurries': 28 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Tetairoa',
    lastName: 'McMillan',
    position: 'WR',
    college: 'Arizona',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 212,
    paiScore: 92,
    tier: 'TOP_5',
    performance: 91,
    athleticism: 93,
    intangibles: 88,
    overallRank: 5,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Dominant big-body receiver with elite contested catch ability. His 6'5\" frame with 4.45 speed is an NFL prototype. Took over games in the Big 12. Route-running improved dramatically as a junior.",
    tags: JSON.stringify(['big-body', 'contested-catch', 'x-receiver', 'red-zone']),
    comparisons: JSON.stringify(['Mike Evans body', "Ja'Marr Chase competitiveness"]),
    collegeStats: JSON.stringify({ 'Receptions': 84, 'Rec Yards': '1,319', 'Rec TD': 8, 'YPC': 15.7 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 5,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Mason',
    lastName: 'Graham',
    position: 'DT',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 318,
    paiScore: 91,
    tier: 'TOP_15',
    performance: 92,
    athleticism: 89,
    intangibles: 91,
    overallRank: 6,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Anchor of Michigan's dominant defensive line. Interior disruptor who collapses the pocket and stuffs the run. Plays with excellent leverage and hand technique. National champion pedigree.",
    tags: JSON.stringify(['interior-disruptor', 'run-stuffer', 'leverage', 'national-champion']),
    comparisons: JSON.stringify(['Chris Jones power', 'Aaron Donald technique']),
    collegeStats: JSON.stringify({ 'Sacks': 5.5, 'TFL': 11, 'Tackles': 44, 'QB Hurries': 18 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 8,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Will',
    lastName: 'Johnson',
    position: 'CB',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'2\"",
    weight: 202,
    paiScore: 90,
    tier: 'TOP_15',
    performance: 89,
    athleticism: 92,
    intangibles: 88,
    overallRank: 7,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: "Prototype press-man corner with ideal NFL size. Physical at the line and fluid in his turn. Michigan's defense asked him to shadow the best receiver every week. Interception production is elite.",
    tags: JSON.stringify(['press-man', 'prototype-size', 'shadow-corner', 'ball-hawk']),
    comparisons: JSON.stringify(['Jalen Ramsey physicality', 'Patrick Surtain technique']),
    collegeStats: JSON.stringify({ 'INT': 5, 'PBU': 14, 'Tackles': 38 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 10,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Will',
    lastName: 'Campbell',
    position: 'OT',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'6\"",
    weight: 323,
    paiScore: 90,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 88,
    intangibles: 90,
    overallRank: 8,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Started at left tackle as a true freshman at LSU. Three-year starter against SEC competition. Massive frame with surprising athleticism. Pass protection is his strength — allowed minimal pressures in 2025.",
    tags: JSON.stringify(['left-tackle', 'sec-tested', 'pass-protector', 'day-1-starter']),
    comparisons: JSON.stringify(['Laremy Tunsil technique', 'Trent Williams power']),
    collegeStats: JSON.stringify({ 'Starts': 39, 'Sacks Allowed': 3, 'Penalties': 7 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 9,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Kelvin',
    lastName: 'Banks',
    position: 'OT',
    college: 'Texas',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'4\"",
    weight: 320,
    paiScore: 89,
    tier: 'TOP_15',
    performance: 88,
    athleticism: 90,
    intangibles: 87,
    overallRank: 9,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: "Texas LT who anchored the offensive line during their SEC transition. Athletic tackle who excels in zone blocking. Footwork and mirror ability are top-tier. Occasionally beaten by pure speed rushers.",
    tags: JSON.stringify(['zone-blocker', 'athletic', 'mirror-ability', 'sec-tested']),
    comparisons: JSON.stringify(['Penei Sewell athleticism']),
    collegeStats: JSON.stringify({ 'Starts': 36, 'Sacks Allowed': 4, 'Penalties': 5 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 12,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Mykel',
    lastName: 'Williams',
    position: 'EDGE',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 265,
    paiScore: 89,
    tier: 'TOP_15',
    performance: 88,
    athleticism: 93,
    intangibles: 84,
    overallRank: 10,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: "Physical freak on Georgia's defensive line. Rotated between DE and DT showing rare versatility. Explosive off the edge with power to bull-rush. Georgia's defense consistently produces NFL talent.",
    tags: JSON.stringify(['versatile-dl', 'power-rusher', 'georgia-pipeline', 'explosive']),
    comparisons: JSON.stringify(['Travon Walker athleticism', 'Aidan Hutchinson motor']),
    collegeStats: JSON.stringify({ 'Sacks': 9, 'TFL': 14, 'Tackles': 52, 'FF': 2 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 11,
    enrichedBy: 'manual',
  },
  // ── TOP_15 continued ──────────────────────────────────────
  {
    firstName: 'Luther',
    lastName: 'Burden',
    position: 'WR',
    college: 'Missouri',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "5'11\"",
    weight: 208,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 88,
    intangibles: 85,
    overallRank: 11,
    positionRank: 2,
    trend: 'STEADY',
    tags: JSON.stringify(['slot-weapon', 'yac-monster', 'versatile', 'return-game']),
    comparisons: JSON.stringify(['Deebo Samuel versatility', 'Tyreek Hill explosiveness']),
    collegeStats: JSON.stringify({ 'Receptions': 86, 'Rec Yards': '1,212', 'Rec TD': 10, 'Rush Yards': 114 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 14,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Malaki',
    lastName: 'Starks',
    position: 'S',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 205,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 87,
    athleticism: 90,
    intangibles: 86,
    overallRank: 12,
    positionRank: 1,
    trend: 'STEADY',
    tags: JSON.stringify(['range', 'ball-hawk', 'tackling', 'leadership']),
    comparisons: JSON.stringify(['Derwin James range', 'Ed Reed instincts']),
    collegeStats: JSON.stringify({ 'INT': 4, 'PBU': 8, 'Tackles': 62, 'FF': 2 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 16,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Tyler',
    lastName: 'Warren',
    position: 'TE',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'6\"",
    weight: 260,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 85,
    intangibles: 88,
    overallRank: 13,
    positionRank: 1,
    trend: 'UP',
    tags: JSON.stringify(['complete-te', 'receiving', 'blocking', 'matchup-nightmare']),
    comparisons: JSON.stringify(['George Kittle all-around', 'Travis Kelce receiving']),
    collegeStats: JSON.stringify({ 'Receptions': 88, 'Rec Yards': '1,049', 'Rec TD': 9 }),
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 1,
    projectedPick: 15,
    enrichedBy: 'manual',
  },
  {
    firstName: 'James',
    lastName: 'Pearce',
    position: 'EDGE',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 243,
    paiScore: 87,
    tier: 'TOP_15',
    performance: 86,
    athleticism: 92,
    intangibles: 82,
    overallRank: 14,
    positionRank: 3,
    trend: 'STEADY',
    tags: JSON.stringify(['speed-rusher', 'bend', 'length', 'raw']),
    comparisons: JSON.stringify(['Will Anderson length', 'Myles Garrett upside']),
    collegeStats: JSON.stringify({ 'Sacks': 10, 'TFL': 15, 'Tackles': 48, 'FF': 3 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 18,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Ashton',
    lastName: 'Jeanty',
    position: 'RB',
    college: 'Boise State',
    conference: 'Mountain West',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "5'9\"",
    weight: 215,
    paiScore: 92,
    tier: 'TOP_15',
    performance: 96,
    athleticism: 92,
    intangibles: 88,
    overallRank: 15,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Heisman finalist who nearly broke Barry Sanders' single-season rushing record. Compact, explosive runner with elite vision and contact balance. The question is positional value, not talent.",
    tags: JSON.stringify(['workhorse', 'contact-balance', 'vision', 'heisman-finalist']),
    comparisons: JSON.stringify(['Saquon Barkley explosiveness', 'Marshawn Lynch contact balance']),
    collegeStats: JSON.stringify({ 'Rush Yards': '2,497', 'Rush TD': 29, 'YPC': 7.1, 'Receptions': 22, 'Rec Yards': 194 }),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 20,
    bullCase: "Jeanty is the best RB prospect since Saquon. Nearly 2,500 yards and 29 TDs. His vision, contact balance, and burst are elite.",
    bearCase: "RB positional value is at an all-time low. Mountain West competition doesn't translate. 5'9\" frame takes punishment.",
    mediationVerdict: "Split. The talent is undeniable but the positional value debate is real. He's RB1 but may slide to mid-first.",
    debateWinner: 'SPLIT',
    enrichedBy: 'manual',
  },
  // ── FIRST_ROUND ───────────────────────────────────────────
  {
    firstName: 'Nic',
    lastName: 'Scourton',
    position: 'EDGE',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'4\"",
    weight: 262,
    paiScore: 86,
    tier: 'FIRST_ROUND',
    performance: 85,
    athleticism: 90,
    intangibles: 82,
    overallRank: 16,
    positionRank: 4,
    trend: 'UP',
    tags: JSON.stringify(['power-rusher', 'sec-tested', 'motor']),
    comparisons: JSON.stringify(['Danielle Hunter build']),
    collegeStats: JSON.stringify({ 'Sacks': 9.5, 'TFL': 13, 'Tackles': 51 }),
    combineInvite: true,
    projectedRound: 1,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jalon',
    lastName: 'Walker',
    position: 'LB',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'2\"",
    weight: 245,
    paiScore: 86,
    tier: 'FIRST_ROUND',
    performance: 85,
    athleticism: 89,
    intangibles: 83,
    overallRank: 17,
    positionRank: 1,
    trend: 'STEADY',
    tags: JSON.stringify(['pass-rush-lb', 'versatile', 'georgia-pedigree']),
    comparisons: JSON.stringify(['Roquan Smith instincts']),
    collegeStats: JSON.stringify({ 'Sacks': 8, 'TFL': 12, 'Tackles': 68, 'INT': 1, 'FF': 2 }),
    combineInvite: true,
    projectedRound: 1,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Colston',
    lastName: 'Loveland',
    position: 'TE',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 245,
    paiScore: 85,
    tier: 'FIRST_ROUND',
    performance: 84,
    athleticism: 88,
    intangibles: 82,
    overallRank: 18,
    positionRank: 2,
    trend: 'UP',
    tags: JSON.stringify(['athletic-te', 'receiving-weapon', 'yac']),
    comparisons: JSON.stringify(['Kyle Pitts athleticism']),
    collegeStats: JSON.stringify({ 'Receptions': 56, 'Rec Yards': '728', 'Rec TD': 5 }),
    combineInvite: true,
    projectedRound: 1,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Morrison',
    position: 'CB',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'0\"",
    weight: 190,
    paiScore: 85,
    tier: 'FIRST_ROUND',
    performance: 84,
    athleticism: 86,
    intangibles: 86,
    overallRank: 19,
    positionRank: 3,
    trend: 'UP',
    tags: JSON.stringify(['ball-hawk', 'technique', 'notre-dame']),
    comparisons: JSON.stringify(['Stephon Gilmore technique']),
    collegeStats: JSON.stringify({ 'INT': 7, 'PBU': 12, 'Tackles': 35 }),
    combineInvite: true,
    projectedRound: 1,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Emeka',
    lastName: 'Egbuka',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'1\"",
    weight: 205,
    paiScore: 84,
    tier: 'FIRST_ROUND',
    performance: 86,
    athleticism: 84,
    intangibles: 82,
    overallRank: 20,
    positionRank: 3,
    trend: 'STEADY',
    tags: JSON.stringify(['route-runner', 'reliable', 'big-game']),
    comparisons: JSON.stringify(['Chris Olave route-running', 'Keenan Allen reliability']),
    collegeStats: JSON.stringify({ 'Receptions': 74, 'Rec Yards': '1,011', 'Rec TD': 10 }),
    combineInvite: true,
    projectedRound: 1,
    enrichedBy: 'manual',
  },
  // ── DAY_2 Prospects ───────────────────────────────────────
  {
    firstName: 'Donovan',
    lastName: 'Jackson',
    position: 'OG',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    height: "6'4\"",
    weight: 320,
    paiScore: 82,
    tier: 'DAY_2',
    performance: 83,
    athleticism: 82,
    intangibles: 80,
    overallRank: 21,
    positionRank: 1,
    trend: 'STEADY',
    tags: JSON.stringify(['mauler', 'run-blocker', 'experienced']),
    collegeStats: JSON.stringify({ 'Starts': 38, 'Sacks Allowed': 2 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Tyleik',
    lastName: 'Williams',
    position: 'DT',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    height: "6'3\"",
    weight: 290,
    paiScore: 81,
    tier: 'DAY_2',
    performance: 82,
    athleticism: 83,
    intangibles: 78,
    overallRank: 22,
    positionRank: 2,
    trend: 'UP',
    tags: JSON.stringify(['penetrating-dt', 'quick-twitch', 'pass-rush']),
    collegeStats: JSON.stringify({ 'Sacks': 7, 'TFL': 12, 'Tackles': 41 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Nick',
    lastName: 'Emmanwori',
    position: 'S',
    college: 'South Carolina',
    conference: 'SEC',
    classYear: 'Junior',
    height: "6'3\"",
    weight: 227,
    paiScore: 80,
    tier: 'DAY_2',
    performance: 78,
    athleticism: 88,
    intangibles: 76,
    overallRank: 23,
    positionRank: 2,
    trend: 'UP',
    tags: JSON.stringify(['physical-safety', 'size', 'run-support']),
    comparisons: JSON.stringify(['Kam Chancellor physicality']),
    collegeStats: JSON.stringify({ 'Tackles': 76, 'INT': 3, 'PBU': 6, 'FF': 2 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Omarion',
    lastName: 'Hampton',
    position: 'RB',
    college: 'North Carolina',
    conference: 'ACC',
    classYear: 'Junior',
    height: "6'0\"",
    weight: 220,
    paiScore: 80,
    tier: 'DAY_2',
    performance: 82,
    athleticism: 82,
    intangibles: 76,
    overallRank: 24,
    positionRank: 2,
    trend: 'STEADY',
    tags: JSON.stringify(['power-back', 'between-tackles', 'workhorse']),
    comparisons: JSON.stringify(['Derrick Henry downhill running']),
    collegeStats: JSON.stringify({ 'Rush Yards': '1,660', 'Rush TD': 15, 'YPC': 5.8 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Shemar',
    lastName: 'Stewart',
    position: 'DT',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    height: "6'6\"",
    weight: 290,
    paiScore: 79,
    tier: 'DAY_2',
    performance: 78,
    athleticism: 85,
    intangibles: 74,
    overallRank: 25,
    positionRank: 3,
    trend: 'UP',
    tags: JSON.stringify(['length', 'upside', 'raw-power']),
    collegeStats: JSON.stringify({ 'Sacks': 5, 'TFL': 10, 'Tackles': 38 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  // Day 2 continued — rounds 2-3
  {
    firstName: 'Shavon',
    lastName: 'Revel',
    position: 'CB',
    college: 'East Carolina',
    conference: 'AAC',
    classYear: 'Senior',
    height: "6'3\"",
    weight: 193,
    paiScore: 78,
    tier: 'DAY_2',
    performance: 77,
    athleticism: 84,
    intangibles: 74,
    overallRank: 26,
    positionRank: 4,
    trend: 'UP',
    tags: JSON.stringify(['length', 'press-corner', 'upside']),
    collegeStats: JSON.stringify({ 'INT': 3, 'PBU': 11, 'Tackles': 42 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jalen',
    lastName: 'Milroe',
    position: 'QB',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Junior',
    height: "6'2\"",
    weight: 225,
    paiScore: 77,
    tier: 'DAY_2',
    performance: 76,
    athleticism: 90,
    intangibles: 68,
    overallRank: 27,
    positionRank: 3,
    trend: 'DOWN',
    tags: JSON.stringify(['dual-threat', 'rushing-qb', 'raw-passer', 'upside']),
    comparisons: JSON.stringify(['Lamar Jackson running ability']),
    collegeStats: JSON.stringify({ 'Pass Yards': '2,652', 'Pass TD': 16, 'INT': 11, 'Rush Yards': 726, 'Rush TD': 10 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Tyler',
    lastName: 'Booker',
    position: 'OG',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Junior',
    height: "6'5\"",
    weight: 325,
    paiScore: 77,
    tier: 'DAY_2',
    performance: 78,
    athleticism: 77,
    intangibles: 76,
    overallRank: 28,
    positionRank: 2,
    trend: 'STEADY',
    tags: JSON.stringify(['mauler', 'road-grader', 'power']),
    collegeStats: JSON.stringify({ 'Starts': 33 }),
    combineInvite: true,
    projectedRound: 2,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Kenneth',
    lastName: 'Grant',
    position: 'DT',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    height: "6'3\"",
    weight: 339,
    paiScore: 76,
    tier: 'DAY_2',
    performance: 77,
    athleticism: 78,
    intangibles: 74,
    overallRank: 29,
    positionRank: 4,
    trend: 'STEADY',
    tags: JSON.stringify(['nose-tackle', 'space-eater', 'run-stuffer']),
    collegeStats: JSON.stringify({ 'Sacks': 3, 'TFL': 8, 'Tackles': 35 }),
    combineInvite: true,
    projectedRound: 3,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Cam',
    lastName: 'Skattebo',
    position: 'RB',
    college: 'Arizona State',
    conference: 'Big 12',
    classYear: 'Senior',
    height: "5'10\"",
    weight: 218,
    paiScore: 79,
    tier: 'DAY_2',
    performance: 84,
    athleticism: 78,
    intangibles: 76,
    overallRank: 30,
    positionRank: 3,
    trend: 'UP',
    tags: JSON.stringify(['do-it-all', 'power-back', 'receiver', 'tough']),
    comparisons: JSON.stringify(['Christian McCaffrey versatility']),
    collegeStats: JSON.stringify({ 'Rush Yards': '1,711', 'Rush TD': 19, 'Receptions': 42, 'Rec Yards': 504 }),
    combineInvite: true,
    projectedRound: 3,
    enrichedBy: 'manual',
  },
];

// ─────────────────────────────────────────────────────────────
// NFL Team Needs (2026 Draft) — seeded with draft order
// ─────────────────────────────────────────────────────────────

export const SEED_NFL_TEAM_NEEDS: Array<{
  teamName: string; abbreviation: string; city: string; conference: string; division: string;
  record: string; draftOrder: number; needs: Record<string, number>; capSpace: string;
}> = [
  // Draft order based on inverse record + playoff results
  { teamName: 'Cleveland Browns', abbreviation: 'CLE', city: 'Cleveland', conference: 'AFC', division: 'North', record: '3-14', draftOrder: 1, needs: { QB: 1, WR: 1, OT: 2, CB: 2, EDGE: 3 }, capSpace: '$35.2M' },
  { teamName: 'New England Patriots', abbreviation: 'NE', city: 'Foxborough', conference: 'AFC', division: 'East', record: '4-13', draftOrder: 2, needs: { QB: 1, WR: 1, OT: 1, CB: 2, DT: 3 }, capSpace: '$68.3M' },
  { teamName: 'New York Giants', abbreviation: 'NYG', city: 'East Rutherford', conference: 'NFC', division: 'East', record: '3-14', draftOrder: 3, needs: { QB: 1, OT: 1, EDGE: 1, WR: 2, CB: 2 }, capSpace: '$42.1M' },
  { teamName: 'Jacksonville Jaguars', abbreviation: 'JAX', city: 'Jacksonville', conference: 'AFC', division: 'South', record: '4-13', draftOrder: 4, needs: { OT: 1, EDGE: 1, WR: 2, S: 2, DT: 2 }, capSpace: '$31.8M' },
  { teamName: 'Tennessee Titans', abbreviation: 'TEN', city: 'Nashville', conference: 'AFC', division: 'South', record: '3-14', draftOrder: 5, needs: { QB: 1, WR: 1, EDGE: 1, CB: 2, OT: 2 }, capSpace: '$52.4M' },
  { teamName: 'Las Vegas Raiders', abbreviation: 'LV', city: 'Las Vegas', conference: 'AFC', division: 'West', record: '4-13', draftOrder: 6, needs: { QB: 1, WR: 1, OT: 1, CB: 1, LB: 2 }, capSpace: '$44.6M' },
  { teamName: 'New York Jets', abbreviation: 'NYJ', city: 'East Rutherford', conference: 'AFC', division: 'East', record: '5-12', draftOrder: 7, needs: { QB: 1, OT: 1, EDGE: 2, WR: 2, IOL: 2 }, capSpace: '$22.3M' },
  { teamName: 'Carolina Panthers', abbreviation: 'CAR', city: 'Charlotte', conference: 'NFC', division: 'South', record: '5-12', draftOrder: 8, needs: { OT: 1, EDGE: 1, WR: 1, CB: 2, S: 2 }, capSpace: '$36.7M' },
  { teamName: 'New Orleans Saints', abbreviation: 'NO', city: 'New Orleans', conference: 'NFC', division: 'South', record: '5-12', draftOrder: 9, needs: { QB: 1, WR: 1, CB: 1, OT: 2, EDGE: 2 }, capSpace: '-$56.2M' },
  { teamName: 'Chicago Bears', abbreviation: 'CHI', city: 'Chicago', conference: 'NFC', division: 'North', record: '5-12', draftOrder: 10, needs: { OT: 1, WR: 1, CB: 1, EDGE: 2, S: 2 }, capSpace: '$58.1M' },
  { teamName: 'San Francisco 49ers', abbreviation: 'SF', city: 'Santa Clara', conference: 'NFC', division: 'West', record: '6-11', draftOrder: 11, needs: { QB: 1, EDGE: 1, CB: 2, OT: 2, IOL: 2 }, capSpace: '$8.4M' },
  { teamName: 'Dallas Cowboys', abbreviation: 'DAL', city: 'Arlington', conference: 'NFC', division: 'East', record: '7-10', draftOrder: 12, needs: { EDGE: 1, DT: 1, S: 1, QB: 2, WR: 2 }, capSpace: '$24.9M' },
  { teamName: 'Miami Dolphins', abbreviation: 'MIA', city: 'Miami', conference: 'AFC', division: 'East', record: '8-9', draftOrder: 13, needs: { OT: 1, EDGE: 1, LB: 1, QB: 2, IOL: 2 }, capSpace: '$18.2M' },
  { teamName: 'Indianapolis Colts', abbreviation: 'IND', city: 'Indianapolis', conference: 'AFC', division: 'South', record: '8-9', draftOrder: 14, needs: { WR: 1, CB: 1, EDGE: 1, OT: 2, S: 2 }, capSpace: '$41.5M' },
  { teamName: 'Arizona Cardinals', abbreviation: 'ARI', city: 'Glendale', conference: 'NFC', division: 'West', record: '8-9', draftOrder: 15, needs: { EDGE: 1, CB: 1, DT: 1, IOL: 2, TE: 2 }, capSpace: '$52.8M' },
  { teamName: 'Cincinnati Bengals', abbreviation: 'CIN', city: 'Cincinnati', conference: 'AFC', division: 'North', record: '9-8', draftOrder: 16, needs: { OT: 1, DT: 1, LB: 1, S: 2, EDGE: 2 }, capSpace: '$33.6M' },
  { teamName: 'Atlanta Falcons', abbreviation: 'ATL', city: 'Atlanta', conference: 'NFC', division: 'South', record: '8-9', draftOrder: 17, needs: { EDGE: 1, DT: 1, CB: 1, S: 2, IOL: 2 }, capSpace: '$17.4M' },
  { teamName: 'Seattle Seahawks', abbreviation: 'SEA', city: 'Seattle', conference: 'NFC', division: 'West', record: '10-7', draftOrder: 18, needs: { OT: 1, DT: 1, CB: 2, EDGE: 2, IOL: 2 }, capSpace: '$25.3M' },
  { teamName: 'Tampa Bay Buccaneers', abbreviation: 'TB', city: 'Tampa', conference: 'NFC', division: 'South', record: '10-7', draftOrder: 19, needs: { DT: 1, EDGE: 1, S: 1, IOL: 2, CB: 2 }, capSpace: '$19.8M' },
  { teamName: 'Denver Broncos', abbreviation: 'DEN', city: 'Denver', conference: 'AFC', division: 'West', record: '10-7', draftOrder: 20, needs: { OT: 1, TE: 1, CB: 2, EDGE: 2, WR: 2 }, capSpace: '$28.7M' },
  { teamName: 'Pittsburgh Steelers', abbreviation: 'PIT', city: 'Pittsburgh', conference: 'AFC', division: 'North', record: '10-7', draftOrder: 21, needs: { QB: 1, WR: 1, OT: 1, IOL: 2, CB: 2 }, capSpace: '$32.1M' },
  { teamName: 'Los Angeles Chargers', abbreviation: 'LAC', city: 'Los Angeles', conference: 'AFC', division: 'West', record: '11-6', draftOrder: 22, needs: { WR: 1, OT: 1, EDGE: 2, DT: 2, LB: 2 }, capSpace: '$14.3M' },
  { teamName: 'Green Bay Packers', abbreviation: 'GB', city: 'Green Bay', conference: 'NFC', division: 'North', record: '11-6', draftOrder: 23, needs: { DT: 1, EDGE: 1, S: 2, IOL: 2, WR: 2 }, capSpace: '$26.5M' },
  { teamName: 'Minnesota Vikings', abbreviation: 'MIN', city: 'Minneapolis', conference: 'NFC', division: 'North', record: '14-3', draftOrder: 24, needs: { IOL: 1, DT: 1, QB: 2, CB: 2, EDGE: 2 }, capSpace: '$42.3M' },
  { teamName: 'Houston Texans', abbreviation: 'HOU', city: 'Houston', conference: 'AFC', division: 'South', record: '10-7', draftOrder: 25, needs: { OT: 1, CB: 1, EDGE: 2, S: 2, IOL: 2 }, capSpace: '$19.4M' },
  { teamName: 'Los Angeles Rams', abbreviation: 'LAR', city: 'Inglewood', conference: 'NFC', division: 'West', record: '10-7', draftOrder: 26, needs: { EDGE: 1, CB: 1, IOL: 1, WR: 2, DT: 2 }, capSpace: '$11.2M' },
  { teamName: 'Baltimore Ravens', abbreviation: 'BAL', city: 'Baltimore', conference: 'AFC', division: 'North', record: '12-5', draftOrder: 27, needs: { CB: 1, EDGE: 1, IOL: 1, WR: 2, S: 2 }, capSpace: '$21.8M' },
  { teamName: 'Buffalo Bills', abbreviation: 'BUF', city: 'Buffalo', conference: 'AFC', division: 'East', record: '13-4', draftOrder: 28, needs: { WR: 1, OT: 1, DT: 2, CB: 2, S: 2 }, capSpace: '$7.6M' },
  { teamName: 'Philadelphia Eagles', abbreviation: 'PHI', city: 'Philadelphia', conference: 'NFC', division: 'East', record: '14-3', draftOrder: 29, needs: { LB: 1, CB: 1, S: 2, DT: 2, WR: 2 }, capSpace: '$15.4M' },
  { teamName: 'Detroit Lions', abbreviation: 'DET', city: 'Detroit', conference: 'NFC', division: 'North', record: '15-2', draftOrder: 30, needs: { CB: 1, EDGE: 1, S: 2, DT: 2, LB: 2 }, capSpace: '$23.9M' },
  { teamName: 'Washington Commanders', abbreviation: 'WAS', city: 'Landover', conference: 'NFC', division: 'East', record: '12-5', draftOrder: 31, needs: { DT: 1, EDGE: 1, WR: 2, CB: 2, TE: 2 }, capSpace: '$55.3M' },
  { teamName: 'Kansas City Chiefs', abbreviation: 'KC', city: 'Kansas City', conference: 'AFC', division: 'West', record: '15-2', draftOrder: 32, needs: { WR: 1, OT: 1, CB: 2, DT: 2, EDGE: 2 }, capSpace: '$13.7M' },
];
