/**
 * Per|Form NFL Draft Data — 2026 NFL Draft
 *
 * Type definitions and production arrays for draft prospects,
 * redraft analysis, and NFL team needs. Populate via the database or
 * POST /api/perform/draft endpoints with real data.
 *
 * NOTE: The 2025 class (Ward, Hunter, Sanders, Carter, etc.) is now in
 * the NFL. See REDRAFT_2025_PROSPECTS for rookie season re-evaluation.
 *
 * Tiers:
 *   TOP_5     — Consensus top 5 pick
 *   TOP_15    — First half of round 1
 *   FIRST_ROUND — Late round 1
 *   DAY_2     — Rounds 2-3
 *   DAY_3     — Rounds 4-7
 *   PRIORITY_UDFA — Top undrafted free agents
 *   UDFA      — Undrafted free agent
 */

export interface SeedDraftProspect {
  firstName: string;
  lastName: string;
  position: string;
  college: string;
  conference?: string;
  classYear: string;
  eligibility?: string;
  height?: string;
  weight?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  overallRank: number;
  positionRank: number;
  trend: string;
  scoutMemo?: string;
  tags?: string;
  comparisons?: string;
  collegeStats?: string;
  combineInvite?: boolean;
  seniorBowl?: boolean;
  projectedRound?: number;
  projectedPick?: number;
  bullCase?: string;
  bearCase?: string;
  mediationVerdict?: string;
  debateWinner?: string;
  enrichedBy?: string;
}

// ─────────────────────────────────────────────────────────────
// 2026 NFL Draft Prospects — populate via POST /api/perform/draft
// ─────────────────────────────────────────────────────────────

export const SEED_DRAFT_PROSPECTS: SeedDraftProspect[] = [
  // ─── TOP 5 ─────────────────────────────────────────────────
  {
    firstName: 'Shedeur',
    lastName: 'Sanders',
    position: 'QB',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-2',
    weight: 215,
    paiScore: 96,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 90,
    intangibles: 97,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Most pro-ready QB in the class. Elite processing, pinpoint accuracy, and poise under pressure. Led Colorado to a historic turnaround.',
    tags: 'Pro-Ready,Accurate,Leader,Poise',
    comparisons: 'Russell Wilson,Drew Brees',
    collegeStats: '{"completionPct":"72.8%","passingYards":"4134","passingTDs":"37","interceptions":"7","qbr":"88.2"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 1,
    bullCase: 'Franchise QB from Day 1. His accuracy, leadership, and processing speed are elite. Will elevate any roster.',
    bearCase: 'Arm strength is merely good, not elite. Some tight-window throws may not translate. Media circus follows.',
    mediationVerdict: 'Bull case wins. Elite accuracy and intangibles trump arm strength concerns.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Travis',
    lastName: 'Hunter',
    position: 'CB/WR',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-1',
    weight: 185,
    paiScore: 98,
    tier: 'TOP_5',
    performance: 99,
    athleticism: 97,
    intangibles: 98,
    overallRank: 2,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Heisman Trophy winner. First true two-way player since Deion Sanders. Elite at BOTH CB and WR. Generational talent.',
    tags: 'Two-Way,Heisman,Generational,Lockdown',
    comparisons: 'Deion Sanders,Champ Bailey',
    collegeStats: '{"interceptions":"5","passBreakups":"12","receptions":"78","receivingYards":"1152","receivingTDs":"14"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 2,
    bullCase: 'Transcendent talent. Even playing one side full-time, he is the best player in the draft. Two-way ability is a bonus.',
    bearCase: 'NFL teams will likely only play him on one side. Durability concerns with two-way workload in college.',
    mediationVerdict: 'Bull case wins overwhelmingly. This is a once-in-a-generation prospect.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Cam',
    lastName: 'Ward',
    position: 'QB',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-2',
    weight: 220,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 95,
    athleticism: 93,
    intangibles: 93,
    overallRank: 3,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Electric playmaker with the biggest arm in the class. Improved dramatically at Miami after WSU/Incarnate Word journey. High ceiling.',
    tags: 'Cannon Arm,Improviser,High Ceiling,Gunslinger',
    comparisons: 'Patrick Mahomes,Brett Favre',
    collegeStats: '{"completionPct":"67.4%","passingYards":"4673","passingTDs":"39","interceptions":"11","qbr":"85.1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 3,
    bullCase: 'Highest ceiling in the draft. His arm talent and improvisational ability create plays that don\'t exist on the whiteboard.',
    bearCase: 'Hero-ball tendencies. Transfer journey raises questions about consistency. Can he read NFL defenses?',
    mediationVerdict: 'Bull case edges it. The arm talent is undeniable and Miami proved he can run a real offense.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Abdul',
    lastName: 'Carter',
    position: 'EDGE',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 252,
    paiScore: 96,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 96,
    intangibles: 94,
    overallRank: 4,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: 'Converted LB who became the most dominant pass rusher in the nation. Explosive first step, bend, and relentless motor.',
    tags: 'Pass Rusher,Converted LB,Motor,Versatile',
    comparisons: 'Micah Parsons,Khalil Mack',
    collegeStats: '{"sacks":"12","TFLs":"22","forcedFumbles":"4","tackles":"58","pressures":"48"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 4,
    bullCase: 'Micah Parsons 2.0. His LB background gives him coverage versatility. Elite pass rush is the most valuable commodity.',
    bearCase: 'Only one full year at EDGE. Technique still developing. Will NFL OTs handle him differently than college?',
    mediationVerdict: 'Bull case wins. The Parsons comp is apt — LB-to-EDGE converts with this athleticism are special.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Tetairoa',
    lastName: 'McMillan',
    position: 'WR',
    college: 'Arizona',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-5',
    weight: 212,
    paiScore: 95,
    tier: 'TOP_5',
    performance: 96,
    athleticism: 94,
    intangibles: 94,
    overallRank: 5,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Massive WR with elite ball skills. Dominates contested catches and has surprising speed for his size. Best WR in the class.',
    tags: 'Contested Catch,X-Receiver,Size,Ball Skills',
    comparisons: 'Mike Evans,AJ Green',
    collegeStats: '{"receptions":"84","receivingYards":"1319","receivingTDs":"12","yardsPerCatch":"15.7"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 6,
    bullCase: 'Matchup-proof WR1. His combination of size, hands, and route-running is rare. Immediate #1 receiver.',
    bearCase: 'Arizona system inflated stats. Can he separate vs NFL press without college-level scheme advantages?',
    mediationVerdict: 'Bull case wins. Size + ball skills + route-running is the complete WR package.',
    debateWinner: 'BULL',
  },

  // ─── TOP 15 ────────────────────────────────────────────────
  {
    firstName: 'Mason',
    lastName: 'Graham',
    position: 'DT',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 318,
    paiScore: 94,
    tier: 'TOP_15',
    performance: 95,
    athleticism: 93,
    intangibles: 93,
    overallRank: 6,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Dominant interior defender. Anchors against the run and generates interior pressure. Michigan\'s defensive anchor.',
    tags: 'Anchor,Interior Pressure,Complete DT,Leader',
    comparisons: 'Chris Jones,DeForest Buckner',
    collegeStats: '{"sacks":"6","TFLs":"14","tackles":"52","pressures":"38"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 7,
    bullCase: 'Three-down DT who can rush the passer from the interior. Rare combination at the position.',
    bearCase: 'Not a flashy sack artist — his impact is felt more in disruption than stats.',
    mediationVerdict: 'Bull case wins. Interior disruption is undervalued in draft analysis.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Mykel',
    lastName: 'Williams',
    position: 'EDGE',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-5',
    weight: 265,
    paiScore: 93,
    tier: 'TOP_15',
    performance: 94,
    athleticism: 94,
    intangibles: 91,
    overallRank: 7,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Massive edge rusher with power and length. Georgia DL factory product. Can collapse the pocket with bull rush or speed.',
    tags: 'Power Rusher,Length,Georgia DL,Versatile',
    comparisons: 'Jared Allen,Trey Hendrickson',
    collegeStats: '{"sacks":"9","TFLs":"18","tackles":"48","forcedFumbles":"3","pressures":"42"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 8,
    bullCase: 'Elite size/power combo. Georgia has produced elite DL at an unprecedented rate. NFL-ready power.',
    bearCase: 'Not elite bend — wins more with power than finesse. Speed rushers project better historically.',
    mediationVerdict: 'Bull case wins. Power + length at his level is a 10-year NFL starter.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Kelvin',
    lastName: 'Banks Jr.',
    position: 'OT',
    college: 'Texas',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-4',
    weight: 320,
    paiScore: 93,
    tier: 'TOP_15',
    performance: 94,
    athleticism: 91,
    intangibles: 93,
    overallRank: 8,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Premier left tackle who has anchored Texas OL for 3 years. Elite pass protection and improving run blocking.',
    tags: 'Left Tackle,Pass Pro,3-Year Starter,Anchor',
    comparisons: 'Tyron Smith,Laremy Tunsil',
    collegeStats: '{"sacksAllowed":"1","gamesStarted":"39","penaltiesPerGame":"0.3"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 10,
    bullCase: 'Franchise LT who has been dominant for 3 seasons. The most proven blindside protector in the class.',
    bearCase: 'Some scouts want more violence in his run blocking. Is he a great pass protector or a great OT?',
    mediationVerdict: 'Bull case wins. Pass protection is the most important OL skill, and he is elite at it.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Ashton',
    lastName: 'Jeanty',
    position: 'RB',
    college: 'Boise State',
    conference: 'Mountain West',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '5-9',
    weight: 215,
    paiScore: 95,
    tier: 'TOP_15',
    performance: 98,
    athleticism: 95,
    intangibles: 92,
    overallRank: 9,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Historic season — nearly broke Barry Sanders\' single-season rushing record. Elite vision, power, and burst. The best RB prospect in years.',
    tags: 'Workhorse,Historic Season,Vision,Power',
    comparisons: 'Marshawn Lynch,Adrian Peterson',
    collegeStats: '{"rushingYards":"2497","rushingTDs":"29","yardsPerCarry":"7.1","receptions":"26","receivingYards":"245"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 12,
    bullCase: 'Generational RB talent. His production transcends the positional value debate. An offense-changer.',
    bearCase: 'RB positional value depresses his draft stock. Mountain West competition level. Heavy workload = mileage.',
    mediationVerdict: 'Bull case edges it. The production is historic. Teams will draft him higher than analytics suggest.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Luther',
    lastName: 'Burden III',
    position: 'WR',
    college: 'Missouri',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '5-11',
    weight: 208,
    paiScore: 92,
    tier: 'TOP_15',
    performance: 93,
    athleticism: 93,
    intangibles: 91,
    overallRank: 10,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Dynamic slot WR with elite YAC ability. Physical for his size. SEC-tested and consistently productive across 3 seasons.',
    tags: 'YAC Monster,Slot,Physical,Route Runner',
    comparisons: 'Tyreek Hill,Steve Smith Sr.',
    collegeStats: '{"receptions":"72","receivingYards":"1082","receivingTDs":"10","yardsPerCatch":"15.0"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 13,
    bullCase: 'Explosive playmaker who creates after the catch. His physicality at 5-11 is rare.',
    bearCase: 'Not a true WR1 — best as slot in the NFL. Size limits his route tree at the next level.',
    mediationVerdict: 'Bull case edges it. Slot receivers are valued in modern NFL and he is elite there.',
    debateWinner: 'BULL',
  },

  // ─── FIRST ROUND ───────────────────────────────────────────
  {
    firstName: 'Jalen',
    lastName: 'Milroe',
    position: 'QB',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-2',
    weight: 225,
    paiScore: 89,
    tier: 'FIRST_ROUND',
    performance: 90,
    athleticism: 93,
    intangibles: 85,
    overallRank: 14,
    positionRank: 3,
    trend: 'DOWN',
    scoutMemo: 'Dual-threat with elite rushing ability for a QB. Arm talent improved under Kalen DeBoer. Inconsistent accuracy still a concern.',
    tags: 'Dual-Threat,Rusher,Inconsistent,Physical',
    comparisons: 'Lamar Jackson,Josh Allen (early)',
    collegeStats: '{"completionPct":"63.2%","passingYards":"3218","passingTDs":"26","interceptions":"9","rushingYards":"724","rushingTDs":"12"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 18,
    bullCase: 'Running ability at QB is a cheat code. If he hits his ceiling as a passer, he is Josh Allen.',
    bearCase: 'Accuracy is a persistent issue. Cannot rely on running long-term in the NFL.',
    mediationVerdict: 'Balanced. High ceiling, low floor. The right coaching staff is essential.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Tyler',
    lastName: 'Warren',
    position: 'TE',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-6',
    weight: 260,
    paiScore: 93,
    tier: 'FIRST_ROUND',
    performance: 94,
    athleticism: 91,
    intangibles: 93,
    overallRank: 11,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: 'Most complete TE in college football. Dominant as a receiver and elite as an inline blocker. Swiss Army knife weapon.',
    tags: 'Complete TE,Blocker,Receiver,Versatile',
    comparisons: 'Travis Kelce,Rob Gronkowski',
    collegeStats: '{"receptions":"88","receivingYards":"1158","receivingTDs":"9","yardsPerCatch":"13.2"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 15,
    bullCase: 'Do-everything TE who transforms an offense. His blocking sets him apart from receiving TEs.',
    bearCase: 'TE is a slow-developing NFL position. May not dominate early.',
    mediationVerdict: 'Bull case wins. Complete TEs with this production are rare. Day 1 contributor.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Will',
    lastName: 'Johnson',
    position: 'CB',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-2',
    weight: 202,
    paiScore: 92,
    tier: 'FIRST_ROUND',
    performance: 93,
    athleticism: 92,
    intangibles: 91,
    overallRank: 12,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Elite press-man corner with ideal size. Physical at the line and smooth in transitions. Michigan shutdown corner.',
    tags: 'Press-Man,Physical,Ball Skills,Shutdown',
    comparisons: 'Jalen Ramsey,Patrick Surtain II',
    collegeStats: '{"interceptions":"3","passBreakups":"14","tackles":"42","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 16,
    bullCase: 'Size + technique + ball skills = CB1. His press ability translates directly to the NFL.',
    bearCase: 'Michigan zone-heavy scheme may not fully showcase man-to-man ability.',
    mediationVerdict: 'Bull case wins. His physical tools and technique make him scheme-versatile.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'James',
    lastName: 'Pearce Jr.',
    position: 'EDGE',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-5',
    weight: 243,
    paiScore: 91,
    tier: 'FIRST_ROUND',
    performance: 92,
    athleticism: 93,
    intangibles: 89,
    overallRank: 13,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: 'Explosive speed rusher with elite bend. Long arms and closing speed create havoc. Tennessee pass-rush menace.',
    tags: 'Speed Rush,Bend,Long Arms,Closer',
    comparisons: 'Danielle Hunter,Jaelan Phillips',
    collegeStats: '{"sacks":"10","TFLs":"16","tackles":"44","forcedFumbles":"3","pressures":"36"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 19,
    bullCase: 'Pure speed rusher with long-arm ability. His get-off is among the best in the class.',
    bearCase: 'Slender frame raises durability questions. Needs to improve against the run.',
    mediationVerdict: 'Bull case edges it. Pass rush is king and his speed off the edge is elite.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Nic',
    lastName: 'Scourton',
    position: 'EDGE',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-4',
    weight: 280,
    paiScore: 91,
    tier: 'FIRST_ROUND',
    performance: 92,
    athleticism: 90,
    intangibles: 90,
    overallRank: 15,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: 'Transferred from Purdue and dominated in the SEC. Power rusher with improving technique.',
    tags: 'Power,Transfer,SEC Tested,Improving',
    comparisons: 'Myles Garrett (lite),Cameron Jordan',
    collegeStats: '{"sacks":"11","TFLs":"19","tackles":"52","forcedFumbles":"2"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 21,
    bullCase: 'Proved he could dominate SEC OTs after the transfer. Power + length combo is rare.',
    bearCase: 'One-year SEC sample size. Was he a scheme fit or a genuine SEC-caliber rusher?',
    mediationVerdict: 'Bull case wins. SEC production validates the talent.',
    debateWinner: 'BULL',
  },

  // ─── DAY 2 ─────────────────────────────────────────────────
  {
    firstName: 'Donovan',
    lastName: 'Jackson',
    position: 'OG',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-4',
    weight: 320,
    paiScore: 88,
    tier: 'DAY_2',
    performance: 90,
    athleticism: 86,
    intangibles: 88,
    overallRank: 22,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Multi-year starter at guard for Ohio State. Consistent, technically sound, and plays with a nasty streak.',
    tags: 'Starter,Consistent,Nasty,Road Grader',
    comparisons: 'Joel Bitonio,Brandon Scherff',
    collegeStats: '{"gamesStarted":"42","sacksAllowed":"2","penaltiesPerGame":"0.4"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 38,
    bullCase: 'Plug-and-play starter at guard immediately. His experience and consistency are rare.',
    bearCase: 'Lacks elite athleticism — may struggle against top-tier interior pass rushers.',
    mediationVerdict: 'Bull case edges it. Proven starters have fewer bust risks.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Morrison',
    position: 'CB',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-0',
    weight: 190,
    paiScore: 89,
    tier: 'DAY_2',
    performance: 90,
    athleticism: 89,
    intangibles: 88,
    overallRank: 20,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Ball-hawk corner who has been a turnover machine at Notre Dame. Elite instincts and break on the ball.',
    tags: 'Ball Hawk,Instincts,Notre Dame,Playmaker',
    comparisons: 'Asante Samuel,Xavien Howard',
    collegeStats: '{"interceptions":"6","passBreakups":"11","tackles":"38","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 35,
    bullCase: 'Turnover production is elite. Instincts like his don\'t come around often.',
    bearCase: 'Slightly undersized for press-man. May be limited to zone-heavy schemes.',
    mediationVerdict: 'Bull case wins. Ball production is the best predictor of NFL CB success.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Tyleik',
    lastName: 'Williams',
    position: 'DT',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-3',
    weight: 305,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 88,
    athleticism: 87,
    intangibles: 86,
    overallRank: 24,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Stout run defender with growing pass rush. Plays next to Mason Graham but holds his own as a standout DT.',
    tags: 'Run Stuffer,Interior,Consistent,Rotation Piece',
    comparisons: 'Sheldon Rankins,Javon Hargrave',
    collegeStats: '{"sacks":"5","TFLs":"12","tackles":"48","pressures":"24"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 42,
    bullCase: 'Proven interior defender from elite program. Will anchor an NFL run defense immediately.',
    bearCase: 'Not a dynamic pass rusher. Role may be limited to early-down run defender.',
    mediationVerdict: 'Balanced. Solid starter or excellent rotational piece — good value in Round 2.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Emeka',
    lastName: 'Egbuka',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-1',
    weight: 205,
    paiScore: 88,
    tier: 'DAY_2',
    performance: 89,
    athleticism: 87,
    intangibles: 88,
    overallRank: 23,
    positionRank: 3,
    trend: 'DOWN',
    scoutMemo: 'Reliable possession receiver who played alongside elite WRs. Great route runner with sure hands. Consistent producer.',
    tags: 'Route Runner,Reliable,Sure Hands,Possession',
    comparisons: 'Keenan Allen,Adam Thielen',
    collegeStats: '{"receptions":"74","receivingYards":"1012","receivingTDs":"10","yardsPerCatch":"13.7"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 45,
    bullCase: 'Floor is a 10-year NFL starter. Route running and hands translate immediately.',
    bearCase: 'Not a true #1 — was the second option at Ohio State behind Jeremiah Smith.',
    mediationVerdict: 'Bull case edges it. Reliable WR2 types have massive NFL value.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Derrick',
    lastName: 'Harmon',
    position: 'DT',
    college: 'Oregon',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-5',
    weight: 310,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 88,
    athleticism: 87,
    intangibles: 86,
    overallRank: 25,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: 'Explosive interior lineman who developed into a dominant force at Oregon. Quick off the snap with natural leverage.',
    tags: 'Explosive,Interior,Quick Twitch,Rising',
    comparisons: 'Grady Jarrett,Jonathan Allen',
    collegeStats: '{"sacks":"7","TFLs":"15","tackles":"46","pressures":"30"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 48,
    bullCase: 'Interior pass rush development trajectory is elite. His best football is ahead of him.',
    bearCase: 'Inconsistent motor at times. Can disappear for stretches of games.',
    mediationVerdict: 'Bull case edges it. The physical tools and development arc favor continued growth.',
    debateWinner: 'BULL',
  },
];

// ─────────────────────────────────────────────────────────────
// 2025 Redraft — rookie season re-evaluation
// ─────────────────────────────────────────────────────────────

export interface RedraftProspect extends SeedDraftProspect {
  nflTeam: string;
  draftPick: string;
  rookieStats?: string;
  rookieGrade: number;
  rookieAssessment?: string;
  injuryNote?: string;
}

export const REDRAFT_2025_PROSPECTS: RedraftProspect[] = [
  {
    firstName: 'Caleb',
    lastName: 'Williams',
    position: 'QB',
    college: 'USC',
    conference: 'Big Ten',
    classYear: 'Senior',
    height: '6-1',
    weight: 215,
    paiScore: 90,
    tier: 'TOP_5',
    performance: 88,
    athleticism: 92,
    intangibles: 90,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Chicago Bears',
    draftPick: '1.01',
    rookieStats: '{"completionPct":"63.1%","passingYards":"3542","passingTDs":"22","interceptions":"10","qbr":"72.8","wins":"7"}',
    rookieGrade: 72,
    rookieAssessment: 'Showed flashes of brilliance but struggled with consistency behind a shaky OL. Second-half surge gives hope. Needs better protection and weapons.',
    scoutMemo: 'Went #1 overall. Had typical rookie QB struggles but showed enough late in the season to justify the pick.',
    comparisons: 'Justin Fields (Year 1)',
  },
  {
    firstName: 'Jayden',
    lastName: 'Daniels',
    position: 'QB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Senior',
    height: '6-4',
    weight: 210,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 94,
    athleticism: 95,
    intangibles: 92,
    overallRank: 2,
    positionRank: 2,
    trend: 'UP',
    nflTeam: 'Washington Commanders',
    draftPick: '1.02',
    rookieStats: '{"completionPct":"69.2%","passingYards":"3568","passingTDs":"25","interceptions":"9","rushingYards":"891","rushingTDs":"6","qbr":"82.4"}',
    rookieGrade: 90,
    rookieAssessment: 'OROY frontrunner. Led Washington to the playoffs as a rookie. Dual-threat ability translated immediately. Franchise QB found.',
    scoutMemo: 'Best rookie QB season since Justin Herbert. Dual-threat game translated perfectly to the NFL.',
    comparisons: 'Lamar Jackson,Kyler Murray',
  },
  {
    firstName: 'Drake',
    lastName: 'Maye',
    position: 'QB',
    college: 'North Carolina',
    conference: 'ACC',
    classYear: 'Junior',
    height: '6-4',
    weight: 230,
    paiScore: 86,
    tier: 'TOP_5',
    performance: 82,
    athleticism: 88,
    intangibles: 87,
    overallRank: 3,
    positionRank: 3,
    trend: 'STEADY',
    nflTeam: 'New England Patriots',
    draftPick: '1.03',
    rookieStats: '{"completionPct":"61.8%","passingYards":"2884","passingTDs":"16","interceptions":"12","qbr":"68.5"}',
    rookieGrade: 65,
    rookieAssessment: 'Rough landing spot. Patriots lack weapons and OL talent. Showed arm talent and toughness but needs a complete overhaul around him.',
    scoutMemo: 'Talent is real but the situation in New England is dire. Needs help everywhere.',
    comparisons: 'Sam Darnold (situation)',
    injuryNote: 'Missed 3 games with knee contusion',
  },
  {
    firstName: 'Marvin',
    lastName: 'Harrison Jr.',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    height: '6-4',
    weight: 205,
    paiScore: 92,
    tier: 'TOP_5',
    performance: 88,
    athleticism: 90,
    intangibles: 93,
    overallRank: 4,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Arizona Cardinals',
    draftPick: '1.04',
    rookieStats: '{"receptions":"68","receivingYards":"1042","receivingTDs":"8","yardsPerCatch":"15.3"}',
    rookieGrade: 80,
    rookieAssessment: 'Started slow but finished strong with Kyler Murray finding chemistry. Elite route-running translated. WR1 production incoming Year 2.',
    scoutMemo: 'Proved he can be a #1 WR in the NFL. Chemistry with Kyler Murray took time but the talent is undeniable.',
    comparisons: 'Marvin Harrison Sr. (ceiling)',
  },
  {
    firstName: 'Joe',
    lastName: 'Alt',
    position: 'OT',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    height: '6-8',
    weight: 322,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 95,
    athleticism: 90,
    intangibles: 95,
    overallRank: 5,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'Los Angeles Chargers',
    draftPick: '1.05',
    rookieStats: '{"gamesStarted":"17","sacksAllowed":"2","penaltiesPerGame":"0.2","pffGrade":"88.4"}',
    rookieGrade: 93,
    rookieAssessment: 'Best rookie OL in a decade. Immediately became the Chargers\' best OL and a top-10 tackle in the NFL. Franchise cornerstone.',
    scoutMemo: 'Lived up to every bit of the hype. Elite from Week 1. All-Pro caliber already.',
    comparisons: 'Quenton Nelson (impact)',
  },
  {
    firstName: 'Malik',
    lastName: 'Nabers',
    position: 'WR',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    height: '6-0',
    weight: 200,
    paiScore: 91,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 93,
    intangibles: 89,
    overallRank: 6,
    positionRank: 2,
    trend: 'UP',
    nflTeam: 'New York Giants',
    draftPick: '1.06',
    rookieStats: '{"receptions":"82","receivingYards":"1178","receivingTDs":"7","yardsPerCatch":"14.4"}',
    rookieGrade: 85,
    rookieAssessment: 'Dominant rookie WR season despite inconsistent QB play. Route running and separation are already elite. Imagine him with a franchise QB.',
    scoutMemo: 'LSU WR pipeline delivers again. Nabers was the best offensive player on the Giants from Day 1.',
    comparisons: "Ja'Marr Chase (trajectory)",
    injuryNote: 'Brief concussion protocol absence Week 4',
  },
  {
    firstName: 'Quinyon',
    lastName: 'Mitchell',
    position: 'CB',
    college: 'Toledo',
    conference: 'MAC',
    classYear: 'Junior',
    height: '5-11',
    weight: 195,
    paiScore: 88,
    tier: 'FIRST_ROUND',
    performance: 88,
    athleticism: 90,
    intangibles: 86,
    overallRank: 7,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'Philadelphia Eagles',
    draftPick: '1.22',
    rookieStats: '{"interceptions":"4","passBreakups":"15","tackles":"56","pffCovGrade":"78.2"}',
    rookieGrade: 82,
    rookieAssessment: 'Stepped into a starting role immediately and held his own. Ball production was elite for a rookie. Eagles secondary got a cornerstone.',
    scoutMemo: 'Small-school prospect who proved he belongs. Physical, competitive, and productive from Day 1.',
    comparisons: 'Sauce Gardner (trajectory)',
  },
];

// ─────────────────────────────────────────────────────────────
// NFL Team Needs — 2026 Draft Order
// Populate via POST /api/perform/draft?action=seed-teams
// ─────────────────────────────────────────────────────────────

export interface TeamNeed {
  team: string;
  abbrev: string;
  projectedPick: number;
  primaryNeeds: string[];
  secondaryNeeds: string[];
  tradeLikelihood: 'LOW' | 'MEDIUM' | 'HIGH';
}

export const NFL_TEAM_NEEDS_2026: TeamNeed[] = [
  { team: 'Tennessee Titans', abbrev: 'TEN', projectedPick: 1, primaryNeeds: ['QB', 'OT', 'WR'], secondaryNeeds: ['EDGE', 'CB'], tradeLikelihood: 'HIGH' },
  { team: 'Cleveland Browns', abbrev: 'CLE', projectedPick: 2, primaryNeeds: ['QB', 'OT', 'EDGE'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'HIGH' },
  { team: 'New York Giants', abbrev: 'NYG', projectedPick: 3, primaryNeeds: ['QB', 'OT', 'EDGE'], secondaryNeeds: ['CB', 'LB'], tradeLikelihood: 'HIGH' },
  { team: 'New England Patriots', abbrev: 'NE', projectedPick: 4, primaryNeeds: ['WR', 'OT', 'EDGE'], secondaryNeeds: ['CB', 'DT'], tradeLikelihood: 'MEDIUM' },
  { team: 'Jacksonville Jaguars', abbrev: 'JAX', projectedPick: 5, primaryNeeds: ['OT', 'EDGE', 'WR'], secondaryNeeds: ['CB', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Las Vegas Raiders', abbrev: 'LV', projectedPick: 6, primaryNeeds: ['QB', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'WR'], tradeLikelihood: 'HIGH' },
  { team: 'New York Jets', abbrev: 'NYJ', projectedPick: 7, primaryNeeds: ['OT', 'QB', 'CB'], secondaryNeeds: ['WR', 'EDGE'], tradeLikelihood: 'MEDIUM' },
  { team: 'Carolina Panthers', abbrev: 'CAR', projectedPick: 8, primaryNeeds: ['OT', 'EDGE', 'WR'], secondaryNeeds: ['DT', 'CB'], tradeLikelihood: 'LOW' },
  { team: 'New Orleans Saints', abbrev: 'NO', projectedPick: 9, primaryNeeds: ['QB', 'WR', 'OT'], secondaryNeeds: ['EDGE', 'CB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Chicago Bears', abbrev: 'CHI', projectedPick: 10, primaryNeeds: ['OT', 'WR', 'CB'], secondaryNeeds: ['EDGE', 'RB'], tradeLikelihood: 'MEDIUM' },
  { team: 'San Francisco 49ers', abbrev: 'SF', projectedPick: 11, primaryNeeds: ['QB', 'OT', 'CB'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Dallas Cowboys', abbrev: 'DAL', projectedPick: 12, primaryNeeds: ['OT', 'DT', 'EDGE'], secondaryNeeds: ['S', 'WR'], tradeLikelihood: 'LOW' },
  { team: 'Miami Dolphins', abbrev: 'MIA', projectedPick: 13, primaryNeeds: ['OT', 'EDGE', 'LB'], secondaryNeeds: ['RB', 'DT'], tradeLikelihood: 'LOW' },
  { team: 'Indianapolis Colts', abbrev: 'IND', projectedPick: 14, primaryNeeds: ['WR', 'CB', 'EDGE'], secondaryNeeds: ['OT', 'DT'], tradeLikelihood: 'LOW' },
  { team: 'Atlanta Falcons', abbrev: 'ATL', projectedPick: 15, primaryNeeds: ['EDGE', 'DT', 'OT'], secondaryNeeds: ['CB', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Arizona Cardinals', abbrev: 'ARI', projectedPick: 16, primaryNeeds: ['CB', 'EDGE', 'OT'], secondaryNeeds: ['DT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Cincinnati Bengals', abbrev: 'CIN', projectedPick: 17, primaryNeeds: ['OT', 'DT', 'CB'], secondaryNeeds: ['EDGE', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Seattle Seahawks', abbrev: 'SEA', projectedPick: 18, primaryNeeds: ['OT', 'EDGE', 'CB'], secondaryNeeds: ['DT', 'WR'], tradeLikelihood: 'MEDIUM' },
  { team: 'Tampa Bay Buccaneers', abbrev: 'TB', projectedPick: 19, primaryNeeds: ['DT', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Denver Broncos', abbrev: 'DEN', projectedPick: 20, primaryNeeds: ['WR', 'OT', 'CB'], secondaryNeeds: ['EDGE', 'TE'], tradeLikelihood: 'MEDIUM' },
  { team: 'Pittsburgh Steelers', abbrev: 'PIT', projectedPick: 21, primaryNeeds: ['QB', 'OT', 'WR'], secondaryNeeds: ['CB', 'DT'], tradeLikelihood: 'HIGH' },
  { team: 'Los Angeles Rams', abbrev: 'LAR', projectedPick: 22, primaryNeeds: ['EDGE', 'CB', 'OT'], secondaryNeeds: ['DT', 'WR'], tradeLikelihood: 'MEDIUM' },
  { team: 'Minnesota Vikings', abbrev: 'MIN', projectedPick: 23, primaryNeeds: ['OT', 'CB', 'EDGE'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Houston Texans', abbrev: 'HOU', projectedPick: 24, primaryNeeds: ['OT', 'EDGE', 'CB'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Green Bay Packers', abbrev: 'GB', projectedPick: 25, primaryNeeds: ['DT', 'EDGE', 'S'], secondaryNeeds: ['OT', 'CB'], tradeLikelihood: 'LOW' },
  { team: 'Los Angeles Chargers', abbrev: 'LAC', projectedPick: 26, primaryNeeds: ['WR', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Baltimore Ravens', abbrev: 'BAL', projectedPick: 27, primaryNeeds: ['CB', 'EDGE', 'WR'], secondaryNeeds: ['OT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Philadelphia Eagles', abbrev: 'PHI', projectedPick: 28, primaryNeeds: ['CB', 'LB', 'EDGE'], secondaryNeeds: ['S', 'WR'], tradeLikelihood: 'MEDIUM' },
  { team: 'Buffalo Bills', abbrev: 'BUF', projectedPick: 29, primaryNeeds: ['OT', 'WR', 'DT'], secondaryNeeds: ['CB', 'EDGE'], tradeLikelihood: 'LOW' },
  { team: 'Washington Commanders', abbrev: 'WAS', projectedPick: 30, primaryNeeds: ['CB', 'EDGE', 'DT'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Detroit Lions', abbrev: 'DET', projectedPick: 31, primaryNeeds: ['CB', 'EDGE', 'DT'], secondaryNeeds: ['LB', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Kansas City Chiefs', abbrev: 'KC', projectedPick: 32, primaryNeeds: ['WR', 'CB', 'EDGE'], secondaryNeeds: ['OT', 'DT'], tradeLikelihood: 'MEDIUM' },
];
