/**
 * ScoutVerify Types — evidence-backed prospect evaluation verification
 *
 * Inspired by the VerifyAI pattern (multimodal content → structured analysis →
 * evidence-backed scoring), applied to sports scouting instead of news.
 */

export interface ScoutVerifyInput {
  prospectName: string;
  videoId?: string;          // Twelve Labs indexed video
  videoUrl?: string;         // URL to index first
  highlightReelUrl?: string; // Specific highlight reel
  position?: string;
  school?: string;
  classYear?: number;
}

export interface ExtractedClaim {
  claim: string;
  timestamp?: number;        // seconds into video
  category: 'stat' | 'skill' | 'comparison' | 'ranking' | 'physical';
  verified: boolean | null;  // null = unverified
  confidence: number;        // 0-100
  evidence?: string;         // source that confirms/denies
}

export interface HighlightBiasReport {
  totalPlaysShown: number;
  estimatedTotalSnaps: number | null;
  snapCoverage: number | null;    // 0-1
  onlyPositivePlays: boolean;
  editingFlags: string[];         // "speed manipulation", "selective angles", etc.
  biasScore: number;              // 0-100 (100 = most biased)
}

export interface HypeAnalysis {
  hypeIndex: number;              // 0-100
  mediaSourcesAnalyzed: number;
  inflatedClaims: string[];
  supportedClaims: string[];
  unknownClaims: string[];
}

export interface ScoutVerifyReport {
  reportId: string;
  prospectName: string;
  position?: string;
  school?: string;
  generatedAt: string;

  // Core outputs
  claims: ExtractedClaim[];
  highlightBias: HighlightBiasReport;
  hypeAnalysis: HypeAnalysis;

  // Scores
  paiConfidence: number;          // 0-100 — how much data supports the grade
  overallVerificationScore: number; // 0-100 — composite

  // Scouting report (generated by Pegasus)
  scoutingReport?: string;
  bullCase?: string;
  bearCase?: string;

  // Pipeline metadata
  videosAnalyzed: number;
  processingTimeMs: number;
}
