// Skills Registry — central index for all Hooks, Tasks, and Skills.
// The ACHEEVY trigger engine scans this registry when classifying user intent.
// Mirrors the Plug Registry pattern from lib/plugs/registry.ts.

export type SkillType = "hook" | "task" | "skill";
export type SkillStatus = "active" | "beta" | "disabled";

export interface SkillDefinition {
  id: string;
  name: string;
  type: SkillType;
  status: SkillStatus;
  triggers: string[];
  description: string;
  execution: {
    target: "api" | "cli" | "persona" | "internal";
    route?: string;
    command?: string;
  };
  priority: "critical" | "high" | "medium" | "low";
  definitionFile: string;
  icon: string;
  color: string;
}

// ─── Full Registry ───────────────────────────────────────────

export const SKILL_REGISTRY: SkillDefinition[] = [
  // ── HOOKS ──────────────────────────────────────────────────
  {
    id: "plug-protocol",
    name: "Plug Protocol",
    type: "hook",
    status: "active",
    triggers: ["build", "spin up", "create", "deploy", "launch", "start", "fabricate", "scaffold"],
    description: "Intercepts build/deploy requests and routes them through the Plug Registry.",
    execution: { target: "internal", route: "/api/plugs/[plugId]" },
    priority: "critical",
    definitionFile: "aims-skills/hooks/plug-protocol.md",
    icon: "plug",
    color: "amber",
  },
  {
    id: "docker-compose",
    name: "Docker Compose Orchestration",
    type: "hook",
    status: "active",
    triggers: ["docker", "container", "compose", "service", "infrastructure", "provision", "vps", "hostinger"],
    description: "Manages Docker Compose services on Hostinger VPS.",
    execution: { target: "cli", command: "docker compose -f infra/docker-compose.yml" },
    priority: "high",
    definitionFile: "aims-skills/hooks/docker-compose.md",
    icon: "container",
    color: "blue",
  },
  {
    id: "github-ops",
    name: "GitHub Operations",
    type: "hook",
    status: "active",
    triggers: ["pr", "pull request", "merge", "branch", "commit", "github", "push", "review", "release"],
    description: "Enforces PR/merge/branch best practices aligned with ORACLE gates.",
    execution: { target: "cli", command: "gh" },
    priority: "high",
    definitionFile: "aims-skills/hooks/github-ops.md",
    icon: "git-branch",
    color: "violet",
  },

  // ── TASKS ──────────────────────────────────────────────────
  {
    id: "remotion",
    name: "Remotion Video Generator",
    type: "task",
    status: "active",
    triggers: ["video", "render", "remotion", "composition", "animation", "clip", "footage", "motion"],
    description: "Generate and render video compositions using Remotion with Gemini scripts.",
    execution: { target: "api", route: "/api/skills/remotion" },
    priority: "medium",
    definitionFile: "aims-skills/tasks/remotion.md",
    icon: "video",
    color: "pink",
  },
  {
    id: "gemini-research",
    name: "Gemini Deep Research",
    type: "task",
    status: "active",
    triggers: ["research", "deep research", "analyze", "report", "investigate", "study", "gemini", "findings"],
    description: "Run deep research queries using Gemini with streaming and structured output.",
    execution: { target: "api", route: "/api/research" },
    priority: "high",
    definitionFile: "aims-skills/tasks/gemini-research.md",
    icon: "search",
    color: "cyan",
  },
  {
    id: "automation-workflow",
    name: "Automation Workflow",
    type: "task",
    status: "active",
    triggers: ["workflow", "automation", "automate", "schedule", "cron", "boomer", "boomer_ang"],
    description: "Trigger and manage workflow automations and Boomer_Ang templates.",
    execution: { target: "api", command: "/api/pipeline/trigger" },
    priority: "high",
    icon: "workflow",
    color: "pink",
  },

  // ── SKILLS ─────────────────────────────────────────────────
  {
    id: "stitch",
    name: "Stitch Design System",
    type: "skill",
    status: "active",
    triggers: ["stitch", "design system", "weave", "persona", "gemini design", "ui design", "design guide"],
    description: "Persona-driven design via Gemini CLI with Nano Banana Pro aesthetic.",
    execution: { target: "cli", command: ". ./stitch.ps1; stitch" },
    priority: "medium",
    definitionFile: "aims-skills/skills/stitch.md",
    icon: "palette",
    color: "emerald",
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    type: "skill",
    status: "active",
    triggers: ["nano banana", "glassmorphism", "ui architect", "acheevy design", "glass panels", "obsidian gold", "brick and window"],
    description: "UI architect persona enforcing obsidian/gold glassmorphism design language.",
    execution: { target: "persona" },
    priority: "high",
    definitionFile: "aims-skills/skills/nano-banana-pro.md",
    icon: "sparkles",
    color: "amber",
  },
  {
    id: "best-practices",
    name: "Best Practices & Standards",
    type: "skill",
    status: "active",
    triggers: ["prd", "sop", "kpi", "okr", "best practice", "standard", "process", "documentation", "template", "checklist", "procedure"],
    description: "Generate PRDs, SOPs, KPI dashboards, OKR frameworks, and ORACLE-aligned checklists.",
    execution: { target: "api", route: "/api/skills/best-practices" },
    priority: "high",
    definitionFile: "aims-skills/skills/best-practices.md",
    icon: "clipboard-check",
    color: "emerald",
  },
  {
    id: "agentic-design-system",
    name: "Agentic Design System",
    type: "skill",
    status: "active",
    triggers: ["agentic ui", "agentic design", "design system", "chat component", "agent card", "streaming text", "chat input", "message list", "badge", "toast", "agent interface", "ui component", "design tokens", "theme bridge"],
    description: "Enterprise-grade AI agent UI components (agentic-ui) with obsidian/gold theme bridge, three-tier token architecture, and RAG-backed design best practices.",
    execution: { target: "internal" },
    priority: "critical",
    definitionFile: "aims-skills/skills/agentic-design-system/SKILL.md",
    icon: "component",
    color: "amber",
  },
  // ── ACHEEVY REVENUE VERTICALS (Phase 3.5) ────────────────────
  // NLP-triggered business builder verticals with R-R-S execution
  {
    id: "vertical-idea-generator",
    name: "Business Idea Generator",
    type: "skill",
    status: "active",
    triggers: ["business ideas", "startup ideas", "what should i build", "suggest ideas", "start a business", "entrepreneur", "side hustle"],
    description: "Generate and validate business ideas with market research and execution plans.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "lightbulb",
    color: "amber",
  },
  {
    id: "vertical-pain-points",
    name: "Pain Points Deep Dive",
    type: "skill",
    status: "active",
    triggers: ["pain points", "problems in", "market gaps", "customer frustrations"],
    description: "Analyze industry pain points and identify business opportunities.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "target",
    color: "red",
  },
  {
    id: "vertical-brand-name",
    name: "Brand Name Generator",
    type: "skill",
    status: "active",
    triggers: ["brand name", "company name", "what to call", "name business"],
    description: "Generate brand names, check domains, and build brand identity packages.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "tag",
    color: "violet",
  },
  {
    id: "vertical-value-prop",
    name: "Value Proposition Builder",
    type: "skill",
    status: "active",
    triggers: ["value proposition", "why us", "unique selling", "usp"],
    description: "Craft compelling value propositions, landing page copy, and messaging.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "megaphone",
    color: "emerald",
  },
  {
    id: "vertical-mvp-plan",
    name: "MVP Launch Plan",
    type: "skill",
    status: "active",
    triggers: ["mvp", "launch plan", "minimum viable", "get started", "first steps"],
    description: "Generate and execute a complete MVP launch plan with code scaffolding.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "rocket",
    color: "blue",
  },
  {
    id: "vertical-persona",
    name: "Customer Persona Builder",
    type: "skill",
    status: "active",
    triggers: ["target customer", "who buys", "ideal customer", "customer persona", "buyer persona"],
    description: "Build detailed customer personas with journey maps and targeting.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "users",
    color: "cyan",
  },
  {
    id: "vertical-social-hooks",
    name: "Social Launch Campaign",
    type: "skill",
    status: "active",
    triggers: ["launch tweet", "social post", "announce", "twitter hook", "x hook"],
    description: "Create viral social media launch campaigns with content calendars.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "share",
    color: "pink",
  },
  {
    id: "vertical-cold-outreach",
    name: "Cold Outreach Engine",
    type: "skill",
    status: "active",
    triggers: ["cold email", "outreach", "pitch email", "reach out"],
    description: "Generate multi-touch outreach sequences with email and LinkedIn templates.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "mail",
    color: "amber",
  },
  {
    id: "vertical-automation",
    name: "Task Automation Builder",
    type: "skill",
    status: "active",
    triggers: ["automate", "save time", "streamline", "repetitive tasks"],
    description: "Build workflow automations connecting your existing tools.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "zap",
    color: "yellow",
  },
  {
    id: "vertical-content-calendar",
    name: "Content Calendar Generator",
    type: "skill",
    status: "active",
    triggers: ["content plan", "posting schedule", "content calendar", "social media plan"],
    description: "Generate 30-day content calendars with copy and scheduling.",
    execution: { target: "api", route: "/acheevy/execute" },
    priority: "high",
    definitionFile: "aims-skills/acheevy-verticals/vertical-definitions.ts",
    icon: "calendar",
    color: "emerald",
  },

  // ── PLATFORM SKILLS (Microsoft Skills format) ──────────────────
  {
    id: "brave-search",
    name: "Brave Search",
    type: "skill",
    status: "active",
    triggers: ["search", "web search", "find online", "look up", "research"],
    description: "Primary web search via Brave Search Pro AI with fallback chain.",
    execution: { target: "api", route: "/api/search" },
    priority: "critical",
    definitionFile: "aims-skills/skills/brave-search/SKILL.md",
    icon: "search",
    color: "orange",
  },
  {
    id: "elevenlabs-voice",
    name: "ElevenLabs Voice",
    type: "skill",
    status: "active",
    triggers: ["voice", "tts", "speak", "text to speech", "read aloud"],
    description: "High-quality TTS using ElevenLabs with persona-correct voices.",
    execution: { target: "api", route: "/api/voice/tts" },
    priority: "high",
    definitionFile: "aims-skills/skills/elevenlabs-voice/SKILL.md",
    icon: "mic",
    color: "violet",
  },
  {
    id: "firebase-data",
    name: "Firebase Data",
    type: "skill",
    status: "active",
    triggers: ["store", "firestore", "firebase", "persist"],
    description: "Firestore operations with tenant isolation and role-based access.",
    execution: { target: "internal" },
    priority: "high",
    definitionFile: "aims-skills/skills/firebase-data/SKILL.md",
    icon: "database",
    color: "amber",
  },
  {
    id: "stripe-billing",
    name: "Stripe Billing",
    type: "skill",
    status: "active",
    triggers: ["payment", "subscribe", "billing", "pricing", "plan"],
    description: "Subscription management and payment processing via Stripe + LUC.",
    execution: { target: "api", route: "/api/billing" },
    priority: "high",
    definitionFile: "aims-skills/skills/stripe-billing/SKILL.md",
    icon: "credit-card",
    color: "indigo",
  },
  {
    id: "claude-4.6",
    name: "Claude 4.6",
    type: "skill",
    status: "active",
    triggers: ["claude", "claude opus", "claude sonnet", "opus 4.6", "sonnet 4.6"],
    description: "Route tasks to optimal Claude model variant with adaptive thinking.",
    execution: { target: "api", route: "/api/llm/claude" },
    priority: "critical",
    definitionFile: "aims-skills/skills/claude-4.6/SKILL.md",
    icon: "brain",
    color: "orange",
  },
  {
    id: "unified-search",
    name: "Unified Search",
    type: "skill",
    status: "active",
    triggers: ["find", "lookup", "research online", "google it"],
    description: "Multi-provider search with automatic fallback across Brave, Tavily, and Serper.",
    execution: { target: "api", route: "/api/search" },
    priority: "high",
    definitionFile: "aims-skills/skills/unified-search/SKILL.md",
    icon: "globe",
    color: "cyan",
  },
  {
    id: "openrouter-llm",
    name: "OpenRouter LLM",
    type: "skill",
    status: "active",
    triggers: ["model", "llm", "openrouter", "which model", "ai model"],
    description: "Select optimal LLM model per task complexity with cost awareness.",
    execution: { target: "api", route: "/api/llm/route" },
    priority: "high",
    definitionFile: "aims-skills/skills/openrouter-llm/SKILL.md",
    icon: "cpu",
    color: "emerald",
  },
  {
    id: "orchestrate-turn",
    name: "Orchestrate Turn",
    type: "skill",
    status: "active",
    triggers: ["user_message", "voice_input", "text_submit", "explicit_continue"],
    description: "Core orchestration: load state, compose prompt, call model, parse tools, stream response.",
    execution: { target: "api", route: "/api/acheevy/orchestrate" },
    priority: "critical",
    definitionFile: "aims-skills/skills/orchestrate-turn/SKILL.md",
    icon: "cpu",
    color: "amber",
  },
  {
    id: "fdh-pipeline",
    name: "FDH Pipeline",
    type: "skill",
    status: "active",
    triggers: ["pipeline", "phase transition", "oracle gate", "pipeline audit"],
    description: "Drive work through three mandatory phases with entry criteria and exit gates.",
    execution: { target: "internal" },
    priority: "critical",
    definitionFile: "aims-skills/skills/fdh-pipeline/SKILL.md",
    icon: "git-branch",
    color: "blue",
  },
  {
    id: "factory-controller",
    name: "Factory Controller",
    type: "skill",
    status: "active",
    triggers: ["factory mode", "always-on", "event source", "auto-approve"],
    description: "Promotes ACHEEVY to always-on factory controller watching events and auto-initiating pipelines.",
    execution: { target: "internal" },
    priority: "critical",
    definitionFile: "aims-skills/skills/factory-controller/SKILL.md",
    icon: "settings",
    color: "red",
  },
  {
    id: "factory-swarm",
    name: "Factory Swarm",
    type: "skill",
    status: "active",
    triggers: ["spec changed", "drift detected", "rewire", "n8n workflow"],
    description: "Auto-create and update n8n workflows and dashboards when specs change.",
    execution: { target: "internal" },
    priority: "high",
    definitionFile: "aims-skills/skills/factory-swarm/SKILL.md",
    icon: "workflow",
    color: "violet",
  },
  {
    id: "claude-agent-loop",
    name: "Claude Agent Loop",
    type: "skill",
    status: "active",
    triggers: ["agent loop", "agent pipeline", "orchestration logic"],
    description: "4-step autonomous agent loop for ACHEEVY orchestration.",
    execution: { target: "internal" },
    priority: "high",
    definitionFile: "aims-skills/skills/claude-agent-loop/SKILL.md",
    icon: "repeat",
    color: "orange",
  },
  {
    id: "auth-flow",
    name: "Auth Flow",
    type: "skill",
    status: "active",
    triggers: ["login", "session", "oauth", "auth provider", "role access"],
    description: "Authentication, session management, and OAuth provider configuration.",
    execution: { target: "internal" },
    priority: "medium",
    definitionFile: "aims-skills/skills/auth-flow/SKILL.md",
    icon: "lock",
    color: "emerald",
  },
  {
    id: "prisma-database",
    name: "Prisma Database",
    type: "skill",
    status: "active",
    triggers: ["database", "schema", "query", "migration", "prisma", "sql"],
    description: "Prisma schema conventions, migration workflow, and query patterns.",
    execution: { target: "internal" },
    priority: "medium",
    definitionFile: "aims-skills/skills/prisma-database/SKILL.md",
    icon: "database",
    color: "blue",
  },
  {
    id: "gcp-services",
    name: "GCP Services",
    type: "skill",
    status: "active",
    triggers: ["gcp", "google cloud", "cloud storage", "vision api", "cloud build"],
    description: "GCP service selection, auth patterns, and cost optimization.",
    execution: { target: "internal" },
    priority: "medium",
    definitionFile: "aims-skills/skills/gcp-services/SKILL.md",
    icon: "cloud",
    color: "blue",
  },
  {
    id: "remotion-video",
    name: "Remotion Video",
    type: "skill",
    status: "active",
    triggers: ["remotion", "video composition", "render video", "animation clip"],
    description: "Remotion v4+ video composition, scene management, and rendering.",
    execution: { target: "api", route: "/api/skills/remotion" },
    priority: "high",
    definitionFile: "aims-skills/skills/remotion-video/SKILL.md",
    icon: "video",
    color: "pink",
  },
  {
    id: "render-conversation-shell",
    name: "Conversation Shell",
    type: "skill",
    status: "active",
    triggers: ["chat", "conversation", "ui shell", "input bar"],
    description: "Multi-device chat UI: history, voice input bar, persona chips, model dropdown.",
    execution: { target: "persona" },
    priority: "high",
    definitionFile: "aims-skills/skills/render-conversation-shell/SKILL.md",
    icon: "message-square",
    color: "cyan",
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    type: "skill",
    status: "active",
    triggers: ["gemini", "gemini 3.1", "gemini pro", "deep reasoning", "long context"],
    description: "Route tasks to Gemini 3.1 Pro with correct thinking level and feature flags.",
    execution: { target: "api", route: "/api/llm/gemini" },
    priority: "high",
    definitionFile: "aims-skills/skills/gemini-3.1-pro/SKILL.md",
    icon: "sparkles",
    color: "blue",
  },
  {
    id: "bytedance-seed-2.0",
    name: "ByteDance Seed 2.0",
    type: "skill",
    status: "active",
    triggers: ["seed", "bytedance", "budget reasoning", "video gen"],
    description: "ByteDance Seed ecosystem for budget frontier reasoning and media generation.",
    execution: { target: "api", route: "/api/llm/seed" },
    priority: "high",
    definitionFile: "aims-skills/skills/bytedance-seed-2.0/SKILL.md",
    icon: "cpu",
    color: "red",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    type: "skill",
    status: "active",
    triggers: ["glm", "glm-5", "zhipu", "z.ai", "chatglm"],
    description: "Budget frontier reasoning via GLM-5 744B MoE model.",
    execution: { target: "api", route: "/api/llm/glm" },
    priority: "high",
    definitionFile: "aims-skills/skills/glm-5/SKILL.md",
    icon: "cpu",
    color: "emerald",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    type: "skill",
    status: "active",
    triggers: ["kimi", "kimi k2.5", "moonshot", "multimodal agent", "vision agent"],
    description: "Moonshot 1T-param multimodal agentic model for visual reasoning and video input.",
    execution: { target: "api", route: "/api/llm/kimi" },
    priority: "high",
    definitionFile: "aims-skills/skills/kimi-k2.5/SKILL.md",
    icon: "eye",
    color: "violet",
  },
  {
    id: "analytics-tracking",
    name: "Analytics Tracking",
    type: "skill",
    status: "active",
    triggers: ["analytics", "tracking", "event tracking", "privacy audit"],
    description: "Privacy-first analytics event tracking for pages and features.",
    execution: { target: "internal" },
    priority: "low",
    definitionFile: "aims-skills/skills/analytics-tracking/SKILL.md",
    icon: "bar-chart",
    color: "cyan",
  },
  {
    id: "stitch-app-factory-voice-ui",
    name: "Stitch App Factory Voice UI",
    type: "skill",
    status: "active",
    triggers: ["app factory ui", "voice ui design", "conversation shell design"],
    description: "Generate cross-device ACHEEVY UI with voice-first Q&A and visible selectors.",
    execution: { target: "persona" },
    priority: "high",
    definitionFile: "aims-skills/skills/stitch-app-factory-voice-ui/SKILL.md",
    icon: "layout",
    color: "emerald",
  },
  {
    id: "stitch-nano-design",
    name: "Stitch Nano Design",
    type: "skill",
    status: "active",
    triggers: ["design plan", "ux design", "nano banana design"],
    description: "Auto-load A.I.M.S. Skill Packs and output production-ready UI/UX directives.",
    execution: { target: "persona" },
    priority: "medium",
    definitionFile: "aims-skills/skills/stitch-nano-design/SKILL.md",
    icon: "palette",
    color: "amber",
  },
  {
    id: "threejs-3d",
    name: "Three.js 3D",
    type: "skill",
    status: "active",
    triggers: ["3d", "three", "webgl", "3d visualization"],
    description: "3D graphics guidance with performance constraints and best practices.",
    execution: { target: "internal" },
    priority: "low",
    definitionFile: "aims-skills/skills/threejs-3d/SKILL.md",
    icon: "box",
    color: "indigo",
  },
  {
    id: "ui-interaction-motion",
    name: "UI Interaction Motion",
    type: "skill",
    status: "active",
    triggers: ["motion", "interaction", "overlay", "drawer", "ui animation"],
    description: "Consistent high-performance UI interaction motion system using Motion.",
    execution: { target: "internal" },
    priority: "medium",
    definitionFile: "aims-skills/skills/ui-interaction-motion/SKILL.md",
    icon: "move",
    color: "pink",
  },

  // ── MCP INTEGRATIONS (SME_Ang domain) ─────────────────────────
  {
    id: "boost-space-automation",
    name: "Boost.space Automation",
    type: "skill",
    status: "active",
    triggers: ["boost space", "boostspace", "data sync", "business data", "connected apps", "single source of truth", "data enrichment"],
    description: "Query, write, and enrich business data across 2000+ connected apps via Boost.space Remote MCP.",
    execution: { target: "api", route: "/api/mcp/boost-space" },
    priority: "high",
    definitionFile: "aims-skills/skills/integrations/boost-space-automation.skill.md",
    icon: "database",
    color: "blue",
  },
  {
    id: "boost-space-deployapps",
    name: "Boost.space Deployapps",
    type: "skill",
    status: "active",
    triggers: ["deploy apps", "deployapps", "integrator", "trigger scenario", "run scenario", "automation scenario", "workflow trigger", "on demand scenario"],
    description: "Trigger On-Demand automation scenarios via Boost.space Integrator MCP with parameterized execution.",
    execution: { target: "api", route: "/api/mcp/boost-integrator" },
    priority: "high",
    definitionFile: "aims-skills/skills/integrations/boost-space-deployapps.skill.md",
    icon: "zap",
    color: "amber",
  },
  {
    id: "magic-ui-components",
    name: "21st.dev Magic UI",
    type: "skill",
    status: "active",
    triggers: ["21st", "21st.dev", "magic component", "magic ui", "/ui", "generate component", "ui component", "component builder", "component inspiration", "logo search"],
    description: "Generate production-grade React/TypeScript UI components from natural language via 21st.dev Magic MCP.",
    execution: { target: "api", route: "/api/mcp/magic-ui" },
    priority: "high",
    definitionFile: "aims-skills/skills/integrations/magic-ui-components.skill.md",
    icon: "sparkles",
    color: "violet",
  },

  // ── OBSERVABILITY & MONITORING ────────────────────────────────
  {
    id: "live-look-in",
    name: "Live Look In",
    type: "skill",
    status: "beta",
    triggers: [
      "live look in", "workspace viewer", "office view", "agent viewer",
      "workforce view", "floor plan", "live view", "agent activity",
      "who is working", "agent monitoring", "digital office", "agent simulation",
      "workforce dashboard", "watch agents", "office floor plan", "boomer_ang viewer",
    ],
    description: "Real-time animated workspace viewer rendering ACHIEVEMOR's digital workforce as characters in a virtual office floor plan. Observe Boomer_Angs, Lil_Hawks, ACHEEVY, and Chicken Hawk working, moving between departments, and completing tasks.",
    execution: { target: "internal", route: "/api/live-look-in/state" },
    priority: "high",
    definitionFile: "aims-skills/skills/live-look-in/SKILL.md",
    icon: "eye",
    color: "cyan",
  },
];

// ─── Lookup Helpers ──────────────────────────────────────────

export function findSkillById(id: string): SkillDefinition | undefined {
  return SKILL_REGISTRY.find((s) => s.id === id);
}

export function findSkillByKeywords(query: string): SkillDefinition | null {
  const lower = query.toLowerCase();

  // Skip the plug-protocol hook -- it's handled separately by matchesPlugProtocol()
  const candidates = SKILL_REGISTRY.filter((s) => s.id !== "plug-protocol" && s.status === "active");

  // Score each candidate by number of trigger matches
  let bestMatch: SkillDefinition | null = null;
  let bestScore = 0;

  for (const skill of candidates) {
    let score = 0;
    for (const trigger of skill.triggers) {
      if (lower.includes(trigger)) {
        score += trigger.length; // Longer trigger matches are weighted higher
      }
    }
    // Priority weight boost
    if (score > 0) {
      const priorityBoost = { critical: 100, high: 10, medium: 5, low: 1 };
      score += priorityBoost[skill.priority];
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = skill;
    }
  }

  return bestMatch;
}

export function getSkillsByType(type: SkillType): SkillDefinition[] {
  return SKILL_REGISTRY.filter((s) => s.type === type);
}

export function getAllActiveSkills(): SkillDefinition[] {
  return SKILL_REGISTRY.filter((s) => s.status === "active");
}
