/**
 * A.I.M.S. Plug Engine — nginx Configurator
 * Auto-generates reverse proxy configs for plug instances
 */

import { writeFile, unlink, mkdir } from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';

const execAsync = promisify(exec);
const PLUGS_CONF_DIR = '/etc/aims/nginx/plugs';

export async function generateNginxConfig(subdomain: string, port: number): Promise<void> {
  await mkdir(PLUGS_CONF_DIR, { recursive: true });

  const config = `
# Auto-generated by A.I.M.S. Plug Engine — ${subdomain}
# DO NOT EDIT MANUALLY — managed by plug-engine
server {
    listen 80;
    server_name ${subdomain}.plugs.plugmein.cloud;

    location / {
        proxy_pass http://host.docker.internal:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location /health {
        proxy_pass http://host.docker.internal:${port}/health;
        proxy_read_timeout 5s;
    }
}
`.trim();

  const confPath = path.join(PLUGS_CONF_DIR, `${subdomain}.conf`);
  await writeFile(confPath, config);
  console.log(`[nginx-config] Written config for ${subdomain} → port ${port}`);

  // Reload nginx if running
  try {
    await execAsync('docker exec aims-vps2-nginx nginx -s reload');
    console.log(`[nginx-config] Reloaded nginx`);
  } catch {
    console.warn(`[nginx-config] Could not reload nginx (may not be running yet)`);
  }
}

export async function removeNginxConfig(subdomain: string): Promise<void> {
  const confPath = path.join(PLUGS_CONF_DIR, `${subdomain}.conf`);
  try {
    await unlink(confPath);
    console.log(`[nginx-config] Removed config for ${subdomain}`);
    await execAsync('docker exec aims-vps2-nginx nginx -s reload').catch(() => {});
  } catch {
    console.warn(`[nginx-config] Config for ${subdomain} not found`);
  }
}
