# =============================================================================
# Chicken Hawk — Cloud Run Service
# =============================================================================
# Sandboxed build execution environment for Chicken Hawk.
# Runs on GCP Cloud Run with scale-to-zero, VPC connector, and full CPU.
#
# Deploy:
#   gcloud run services replace infra/gcp/chicken-hawk-cloudrun-service.yaml \
#     --region us-central1 --project aims-aimanagedsolutions
#
# First time — create secrets:
#   echo -n "YOUR_KEY" | gcloud secrets create openrouter-api-key --data-file=-
#   echo -n "YOUR_TOKEN" | gcloud secrets create chickenhawk-gateway-token --data-file=-
# =============================================================================

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chicken-hawk
  labels:
    aims.service: chicken-hawk
    aims.tier: build-execution
  annotations:
    run.googleapis.com/ingress: internal          # Never publicly accessible
    run.googleapis.com/vpc-access-connector: aims-vpc-connector
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"     # Scale to zero when idle
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false" # Full CPU during builds
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 1                     # One build per instance
      timeoutSeconds: 3600                        # 60 min max per build
      serviceAccountName: chicken-hawk@aims-aimanagedsolutions.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/aims-aimanagedsolutions/aims/chicken-hawk:latest
          ports:
            - containerPort: 4001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "4001"
            - name: FIREBASE_PROJECT_ID
              value: aims-aimanagedsolutions
            - name: BYTEROUTER_ENDPOINT
              value: http://byterover.internal:7000
            - name: LUC_ENGINE_URL
              value: http://luc-engine.internal:9010
            - name: AUDIT_SERVICE_URL
              value: http://localhost:4003
            - name: POLICY_SERVICE_URL
              value: http://localhost:4002
            - name: UEF_GATEWAY_URL
              value: https://plugmein.cloud/api
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openrouter-api-key
                  key: latest
            - name: CHICKENHAWK_GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chickenhawk-gateway-token
                  key: latest
          resources:
            limits:
              memory: 4Gi
              cpu: "4"
          startupProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            periodSeconds: 30
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
