import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import { v4 as uuidv4 } from 'uuid';
import { ACPStandardizedRequest, ACPResponse } from './acp/types';
import { LUCEngine } from './luc';
import prisma from './lib/db';
import { iiAgentRouter, getIIAgentClient } from './ii-agent';
import { openclawRouter } from './openclaw/router';
import { acheevyRouter } from './acheevy/router';
import { Oracle } from './oracle';

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(bodyParser.json());

// --------------------------------------------------------------------------
// Health Check
// --------------------------------------------------------------------------
app.get('/health', (req, res) => {
  res.json({ status: 'UEF Gateway Online', layer: 2 });
});

// --------------------------------------------------------------------------
// II-Agent Routes (Autonomous Execution Engine - wrapped as ACHEEVY)
// --------------------------------------------------------------------------
app.use('/ii-agent', iiAgentRouter);

// --------------------------------------------------------------------------
// ACHEEVY Orchestrator (Intent routing and execution)
// --------------------------------------------------------------------------
app.use('/acheevy', acheevyRouter);

// --------------------------------------------------------------------------
// OpenClaw Channel Routes (Multi-channel messaging)
// --------------------------------------------------------------------------
app.use('/api/channel', openclawRouter);

// --------------------------------------------------------------------------
// Intent-Based Execution Plan Generator
// --------------------------------------------------------------------------
function generateExecutionPlan(intent: string, message: string): { steps: string[]; estimatedDuration: string } {
  switch (intent) {
    case 'BUILD_PLUG':
      return {
        steps: [
          'Parse build requirements',
          'Route to CTO_Ang department',
          'Spawn CTOExpert_Ang for architecture review',
          'Generate implementation spec',
          'Queue build task for ACHEEVY',
          'Execute autonomous build',
          'Run ORACLE 7-Gate verification',
          'Deploy to staging'
        ],
        estimatedDuration: '15-30 minutes'
      };
    case 'RESEARCH':
      return {
        steps: [
          'Analyze research query',
          'Route to CPO_Ang department',
          'Spawn research agents',
          'Gather and synthesize sources',
          'Generate comprehensive report',
          'Run ORACLE validation'
        ],
        estimatedDuration: '5-10 minutes'
      };
    case 'AGENTIC_WORKFLOW':
      return {
        steps: [
          'Parse workflow specification',
          'Route to COO_Ang department',
          'Design automation pipeline',
          'Configure triggers and actions',
          'Test workflow execution',
          'Deploy to Automation Engine'
        ],
        estimatedDuration: '10-20 minutes'
      };
    case 'CHAT':
      return {
        steps: [
          'Process natural language',
          'Route to appropriate department',
          'Generate ACHEEVY response',
          'Apply personality and branding'
        ],
        estimatedDuration: '2-5 seconds'
      };
    case 'ESTIMATE_ONLY':
    default:
      return {
        steps: [
          'Analyze intent',
          'Calculate LUC cost estimate',
          'Generate quote variants',
          'Return estimate (no execution)'
        ],
        estimatedDuration: '1 second'
      };
  }
}

// --------------------------------------------------------------------------
// Intent-Based Response Message Generator
// --------------------------------------------------------------------------
function generateResponseMessage(intent: string, oraclePassed: boolean): string {
  if (!oraclePassed) {
    return 'Request did not pass ORACLE 7-Gate verification. Please review and try again.';
  }

  switch (intent) {
    case 'BUILD_PLUG':
      return 'Build request received. CTO_Ang is reviewing architecture. ACHEEVY will orchestrate the autonomous build.';
    case 'RESEARCH':
      return 'Research task queued. CPO_Ang team is gathering sources. Comprehensive report incoming.';
    case 'AGENTIC_WORKFLOW':
      return 'Workflow design initiated. COO_Ang is configuring the automation pipeline.';
    case 'CHAT':
      return 'ACHEEVY has processed your request. Activity breeds Activity!';
    case 'ESTIMATE_ONLY':
    default:
      return 'LUC Quote generated by Bett-Ann_Ang. Ready for execution when you are.';
  }
}

// --------------------------------------------------------------------------
// ACP Ingress (Layer 1)
// --------------------------------------------------------------------------
app.post('/ingress/acp', async (req, res) => {
  try {
    const rawBody = req.body;
    
    // 1. Normalize Request (with budget and metadata passthrough)
    const acpReq: ACPStandardizedRequest = {
      reqId: uuidv4(),
      userId: rawBody.userId || 'anon',
      sessionId: rawBody.sessionId || 'sched-1',
      timestamp: new Date().toISOString(),
      intent: rawBody.intent || 'ESTIMATE_ONLY',
      naturalLanguage: rawBody.message || '',
      channel: rawBody.channel || 'WEB',
      budget: rawBody.budget || undefined,
      metadata: rawBody.metadata || undefined
    };

    console.log(`[UEF] Received ACP Request: ${acpReq.reqId} - ${acpReq.intent}`);

    // 2. Persistent Logging (Async)
    prisma.log.create({
      data: {
        id: acpReq.reqId,
        userId: acpReq.userId,
        intent: acpReq.intent,
        message: acpReq.naturalLanguage,
        status: 'RECEIVED'
      }
    }).catch((err: any) => console.error('[DB] Failed to log request:', err.message));

    // 3. LUC Estimate
    const quote = LUCEngine.estimate(acpReq.naturalLanguage);

    // 4. Generate Intent-Based Execution Plan
    const executionPlan = generateExecutionPlan(acpReq.intent, acpReq.naturalLanguage);

    // 5. Run ORACLE 7-Gate Verification
    const oracleResult = await Oracle.runGates(acpReq, { quote });

    // 6. Construct Response
    const response: ACPResponse = {
      reqId: acpReq.reqId,
      status: oracleResult.passed ? 'SUCCESS' : 'ORACLE_FAILED',
      message: generateResponseMessage(acpReq.intent, oracleResult.passed),
      quote: quote,
      executionPlan: executionPlan,
      oracle: {
        passed: oracleResult.passed,
        score: oracleResult.score,
        gates: oracleResult.gateResults,
        failures: oracleResult.gateFailures
      }
    };

    // 7. Update log status (Async)
    prisma.log.update({
      where: { id: acpReq.reqId },
      data: { 
        status: oracleResult.passed ? 'ORACLE_PASSED' : 'ORACLE_FAILED',
      }
    }).catch((err: any) => console.error('[DB] Failed to update log:', err.message));

    res.json(response);

  } catch (error: any) {
    console.error('ACP Ingress Error:', error);
    res.status(500).json({ status: 'ERROR', message: error.message });
  }
});

// --------------------------------------------------------------------------
// Start Server
// --------------------------------------------------------------------------
app.listen(PORT, () => {
  console.log(`\n>>> UEF Gateway (Layer 2) running on port ${PORT}`);
  console.log(`>>> ACP Ingress available at http://localhost:${PORT}/ingress/acp`);
  console.log(`>>> II-Agent (ACHEEVY) API available at http://localhost:${PORT}/ii-agent`);
  console.log(`>>> ACHEEVY Orchestrator available at http://localhost:${PORT}/acheevy`);
  console.log(`>>> ORACLE 7-Gate verification: ACTIVE`);
  
  // Initialize II-Agent connection on startup (non-blocking)
  getIIAgentClient().connect().catch(() => {
    console.log('[II-Agent] Will connect when first request arrives');
  });
});
